--USE ex_tecdocs_new
--GO

PRINT 'Дропаем форейн кеи'
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ART_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_BRANDS') ALTER TABLE
dbo.TECDOC_TOF_ART_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_BRANDS
GO




IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'IX_TECDOC_TOF_BRANDS') DROP INDEX IX_TECDOC_TOF_BRANDS ON dbo.TECDOC_TOF_BRANDS
CREATE UNIQUE NONCLUSTERED INDEX IX_TECDOC_TOF_BRANDS ON dbo.TECDOC_TOF_BRANDS 
(
	BRA_MF_NR ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_INFO DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_INFO DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_CRITERIA') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_CRITERIA
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ENGINES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ENGINES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_TYPES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_TYPES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LISTS DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES1') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LISTS DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES1
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_ARTICLE_LISTS DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ARTICLES_TECDOC_TOF_SUPPLIERS') ALTER TABLE
dbo.TECDOC_TOF_ARTICLES DROP CONSTRAINT
FK_TECDOC_TOF_ARTICLES_TECDOC_TOF_SUPPLIERS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_DES_TEXTS') ALTER TABLE
dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS DROP CONSTRAINT
FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_DES_TEXTS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_LANGUAGES') ALTER TABLE
dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS DROP CONSTRAINT
FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_LANGUAGES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_DESIGNATIONS_TECDOC_TOF_DES_TEXTS') ALTER TABLE
dbo.TECDOC_TOF_DESIGNATIONS DROP CONSTRAINT
FK_TECDOC_TOF_DESIGNATIONS_TECDOC_TOF_DES_TEXTS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_ENGINES_TECDOC_TOF_MANUFACTURERS') ALTER TABLE
dbo.TECDOC_TOF_ENGINES DROP CONSTRAINT
FK_TECDOC_TOF_ENGINES_TECDOC_TOF_MANUFACTURERS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_GRAPHICS_TECDOC_TOF_DOC_TYPES') ALTER TABLE
dbo.TECDOC_TOF_GRAPHICS DROP CONSTRAINT
FK_TECDOC_TOF_GRAPHICS_TECDOC_TOF_DOC_TYPES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART DROP CONSTRAINT
FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART DROP CONSTRAINT
FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART_GA DROP CONSTRAINT
FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART_GA DROP CONSTRAINT
FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_SUPPLIERS') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART_GA DROP CONSTRAINT
FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_SUPPLIERS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_GA_STR DROP CONSTRAINT
FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_SEARCH_TREE') ALTER TABLE
dbo.TECDOC_TOF_LINK_GA_STR DROP CONSTRAINT
FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_SEARCH_TREE
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_GRA_ART_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_GRA_ART DROP CONSTRAINT
FK_TECDOC_TOF_LINK_GRA_ART_TECDOC_TOF_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_LINK_ART') ALTER TABLE
dbo.TECDOC_TOF_LINK_GRA_LA DROP CONSTRAINT
FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_LINK_ART
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_TYPES') ALTER TABLE
dbo.TECDOC_TOF_LINK_GRA_LA DROP CONSTRAINT
FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_TYPES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_LINK_LA_TYP DROP CONSTRAINT
FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_GENERIC_ARTICLES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_LINK_ART') ALTER TABLE
dbo.TECDOC_TOF_LINK_LA_TYP DROP CONSTRAINT
FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_LINK_ART
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_SUPPLIERS') ALTER TABLE
dbo.TECDOC_TOF_LINK_LA_TYP DROP CONSTRAINT
FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_SUPPLIERS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES') ALTER TABLE
dbo.TECDOC_TOF_LINK_LA_TYP DROP CONSTRAINT
FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS') ALTER TABLE
dbo.TECDOC_TOF_MANUFACTURERS DROP CONSTRAINT
FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES') ALTER TABLE
dbo.TECDOC_TOF_MOD_TYP_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS') ALTER TABLE
dbo.TECDOC_TOF_MODELS DROP CONSTRAINT
FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE') ALTER TABLE
dbo.TECDOC_TOF_STR_FAMILY_TREE DROP CONSTRAINT
FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1') ALTER TABLE
dbo.TECDOC_TOF_STR_FAMILY_TREE DROP CONSTRAINT
FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1
GO


IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES') ALTER TABLE
dbo.TECDOC_TOF_STR_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE') ALTER TABLE
dbo.TECDOC_TOF_STR_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1') ALTER TABLE
dbo.TECDOC_TOF_STR_LOOKUP DROP CONSTRAINT
FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS') ALTER TABLE
dbo.TECDOC_TOF_TEXT_MODULES DROP CONSTRAINT
FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS') ALTER TABLE
dbo.TECDOC_TOF_TYPES DROP CONSTRAINT
FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES') ALTER TABLE
dbo.TECDOC_TOF_SUPPLIERS DROP CONSTRAINT
FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE name =
'FK_TECDOC_TOF_SUPERSEDED_ARTICLES_TECDOC_TOF_ARTICLES') ALTER TABLE
dbo.dbo.TECDOC_TOF_SUPERSEDED_ARTICLES DROP CONSTRAINT
FK_TECDOC_TOF_SUPERSEDED_ARTICLES_TECDOC_TOF_ARTICLES
GO

---------------------------------------------
--PK
---------------------------------------------

PRINT 'Создаем праймари кей PK_TECDOC_TOF_ARTICLES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name = 'PK_TECDOC_TOF_ARTICLES') ALTER TABLE dbo.TECDOC_TOF_ARTICLES DROP CONSTRAINT PK_TECDOC_TOF_ARTICLES
ALTER TABLE dbo.TECDOC_TOF_ARTICLES ADD  CONSTRAINT PK_TECDOC_TOF_ARTICLES PRIMARY KEY CLUSTERED 
(
	ART_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_BRANDS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name = 'PK_TECDOC_TOF_BRANDS') ALTER TABLE dbo.TECDOC_TOF_BRANDS DROP CONSTRAINT PK_TECDOC_TOF_BRANDS
ALTER TABLE dbo.TECDOC_TOF_BRANDS ADD CONSTRAINT PK_TECDOC_TOF_BRANDS PRIMARY KEY CLUSTERED 
(
	BRA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_COUNTRIES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name = 'PK_TECDOC_TOF_COUNTRIES') ALTER TABLE dbo.TECDOC_TOF_COUNTRIES DROP CONSTRAINT PK_TECDOC_TOF_COUNTRIES
ALTER TABLE dbo.TECDOC_TOF_COUNTRIES ADD  CONSTRAINT PK_TECDOC_TOF_COUNTRIES PRIMARY KEY CLUSTERED 
(
	COU_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_CRITERIA'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_CRITERIA') ALTER TABLE
dbo.TECDOC_TOF_CRITERIA DROP CONSTRAINT
PK_TECDOC_TOF_CRITERIA
ALTER TABLE dbo.TECDOC_TOF_CRITERIA ADD  CONSTRAINT PK_TECDOC_TOF_CRITERIA PRIMARY KEY CLUSTERED 
(
	CRI_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_DES_TEXTS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_DES_TEXTS') ALTER TABLE
dbo.TECDOC_TOF_DES_TEXTS DROP CONSTRAINT
PK_TECDOC_TOF_DES_TEXTS
ALTER TABLE dbo.TECDOC_TOF_DES_TEXTS ADD CONSTRAINT PK_TECDOC_TOF_DES_TEXTS PRIMARY KEY CLUSTERED 
(
	TEX_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_DOC_TYPES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_DOC_TYPES') ALTER TABLE
dbo.TECDOC_TOF_DOC_TYPES DROP CONSTRAINT
PK_TECDOC_TOF_DOC_TYPES
ALTER TABLE dbo.TECDOC_TOF_DOC_TYPES ADD CONSTRAINT PK_TECDOC_TOF_DOC_TYPES PRIMARY KEY CLUSTERED 
(
	DOC_TYPE ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_ENGINES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_ENGINES') ALTER TABLE
dbo.TECDOC_TOF_ENGINES DROP CONSTRAINT
PK_TECDOC_TOF_ENGINES
ALTER TABLE dbo.TECDOC_TOF_ENGINES ADD  CONSTRAINT PK_TECDOC_TOF_ENGINES PRIMARY KEY CLUSTERED 
(
	ENG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_GENERIC_ARTICLES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_GENERIC_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_GENERIC_ARTICLES DROP CONSTRAINT
PK_TECDOC_TOF_GENERIC_ARTICLES
ALTER TABLE dbo.TECDOC_TOF_GENERIC_ARTICLES ADD  CONSTRAINT PK_TECDOC_TOF_GENERIC_ARTICLES PRIMARY KEY CLUSTERED 
(
	GA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_LANGUAGES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_LANGUAGES') ALTER TABLE
dbo.TECDOC_TOF_LANGUAGES DROP CONSTRAINT
PK_TECDOC_TOF_LANGUAGES
ALTER TABLE dbo.TECDOC_TOF_LANGUAGES ADD  CONSTRAINT PK_TECDOC_TOF_LANGUAGES PRIMARY KEY CLUSTERED 
(
	LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_LA_ID'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_LA_ID') ALTER TABLE
dbo.TECDOC_TOF_LINK_ART DROP CONSTRAINT
PK_LA_ID
ALTER TABLE dbo.TECDOC_TOF_LINK_ART ADD  CONSTRAINT PK_LA_ID PRIMARY KEY CLUSTERED 
(
	LA_ID ASC
)WITH (PAD_INDEX  = ON, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_MANUFACTURERS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_MANUFACTURERS') ALTER TABLE
dbo.TECDOC_TOF_MANUFACTURERS DROP CONSTRAINT
PK_TECDOC_TOF_MANUFACTURERS
ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS ADD  CONSTRAINT PK_TECDOC_TOF_MANUFACTURERS PRIMARY KEY CLUSTERED 
(
	MFA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_MODELS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_MODELS') ALTER TABLE
dbo.TECDOC_TOF_MODELS DROP CONSTRAINT
PK_TECDOC_TOF_MODELS
ALTER TABLE dbo.TECDOC_TOF_MODELS ADD  CONSTRAINT PK_TECDOC_TOF_MODELS PRIMARY KEY CLUSTERED 
(
	MOD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_SEARCH_TREE'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_SEARCH_TREE') ALTER TABLE
dbo.TECDOC_TOF_SEARCH_TREE DROP CONSTRAINT
PK_TECDOC_TOF_SEARCH_TREE
ALTER TABLE dbo.TECDOC_TOF_SEARCH_TREE ADD  CONSTRAINT PK_TECDOC_TOF_SEARCH_TREE PRIMARY KEY CLUSTERED 
(
	STR_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_TEXT_MODULE_TEXTS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_TEXT_MODULE_TEXTS') ALTER TABLE
dbo.TECDOC_TOF_TEXT_MODULE_TEXTS DROP CONSTRAINT
PK_TECDOC_TOF_TEXT_MODULE_TEXTS
ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULE_TEXTS ADD  CONSTRAINT PK_TECDOC_TOF_TEXT_MODULE_TEXTS PRIMARY KEY CLUSTERED 
(
	TMT_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_TEXT_MODULES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_TEXT_MODULES') ALTER TABLE
dbo.TECDOC_TOF_TEXT_MODULES DROP CONSTRAINT
PK_TECDOC_TOF_TEXT_MODULES
ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES ADD  CONSTRAINT PK_TECDOC_TOF_TEXT_MODULES PRIMARY KEY CLUSTERED 
(
	TMO_ID ASC,
	TMO_LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_TYPES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_TYPES') ALTER TABLE
dbo.TECDOC_TOF_TYPES DROP CONSTRAINT
PK_TECDOC_TOF_TYPES
ALTER TABLE dbo.TECDOC_TOF_TYPES ADD  CONSTRAINT PK_TECDOC_TOF_TYPES PRIMARY KEY CLUSTERED 
(
	TYP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_SUPPLIERS'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_SUPPLIERS') ALTER TABLE
dbo.TECDOC_TOF_SUPPLIERS DROP CONSTRAINT
PK_TECDOC_TOF_SUPPLIERS
ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS ADD  CONSTRAINT PK_TECDOC_TOF_SUPPLIERS PRIMARY KEY CLUSTERED 
(
	SUP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Создаем праймари кей PK_TECDOC_TOF_SUPERSEDED_ARTICLES'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_SUPERSEDED_ARTICLES') ALTER TABLE
dbo.TECDOC_TOF_SUPERSEDED_ARTICLES DROP CONSTRAINT
PK_TECDOC_TOF_SUPERSEDED_ARTICLES
ALTER TABLE TECDOC_TOF_SUPERSEDED_ARTICLES ADD CONSTRAINT PK_TECDOC_TOF_SUPERSEDED_ARTICLES PRIMARY KEY CLUSTERED 
(
	[SUA_ART_ID] ASC,
	[SUA_NUMBER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

---------------------------------------------
--FK
---------------------------------------------

SET ANSI_PADDING OFF
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES'
GO

ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES FOREIGN KEY(LAT_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP CHECK CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS'
GO

ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS WITH CHECK ADD CONSTRAINT FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS FOREIGN KEY(MFA_MF_NR)
REFERENCES dbo.TECDOC_TOF_BRANDS (BRA_MF_NR)
GO
ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS CHECK CONSTRAINT FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES'
GO

ALTER TABLE dbo.TECDOC_TOF_MOD_TYP_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES FOREIGN KEY(MTL_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_MOD_TYP_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS'
GO

ALTER TABLE dbo.TECDOC_TOF_MODELS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS FOREIGN KEY(MOD_MFA_ID)
REFERENCES dbo.TECDOC_TOF_MANUFACTURERS (MFA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_MODELS CHECK CONSTRAINT FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE'
GO

ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE FOREIGN KEY(SFT_ANCESTOR_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE CHECK CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1'
GO

ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1 FOREIGN KEY(SFT_DESCENDANT_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE CHECK CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES'
GO

ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES FOREIGN KEY(STL_LNG_ID)
REFERENCES dbo.TECDOC_TOF_LANGUAGES (LNG_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE'
GO

ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE FOREIGN KEY(STL_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1'
GO

ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1 FOREIGN KEY(STL_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS'
GO

ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS FOREIGN KEY(TMO_TMT_ID)
REFERENCES dbo.TECDOC_TOF_TEXT_MODULE_TEXTS (TMT_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES CHECK CONSTRAINT FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS'
GO

ALTER TABLE dbo.TECDOC_TOF_TYPES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS FOREIGN KEY(TYP_MOD_ID)
REFERENCES dbo.TECDOC_TOF_MODELS (MOD_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_TYPES CHECK CONSTRAINT FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES'
GO

ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS  WITH NOCHECK ADD  CONSTRAINT FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES FOREIGN KEY(SUP_COU_ID)
REFERENCES dbo.TECDOC_TOF_COUNTRIES (COU_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS NOCHECK CONSTRAINT FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES 
GO

PRINT 'Создаем форейн кей FK_TECDOC_TOF_SUPERSEDED_ARTICLES_TECDOC_TOF_ARTICLES'
GO

ALTER TABLE dbo.TECDOC_TOF_SUPERSEDED_ARTICLES WITH CHECK ADD CONSTRAINT FK_TECDOC_TOF_SUPERSEDED_ARTICLES_TECDOC_TOF_ARTICLES FOREIGN KEY(SUA_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_SUPERSEDED_ARTICLES CHECK CONSTRAINT FK_TECDOC_TOF_SUPERSEDED_ARTICLES_TECDOC_TOF_ARTICLES
GO

--------------------------------------------
--Custom
---------------------------------------------

IF OBJECT_ID('Custom.CountryDeliveries', 'U') IS NOT NULL DROP TABLE Custom.CountryDeliveries
--IF OBJECT_ID('Custom.VisibleItems', 'U') IS NOT NULL DROP TABLE Custom.VisibleItems
IF OBJECT_ID('Custom.DenormalizedDesTexts', 'U') IS NOT NULL DROP TABLE Custom.DenormalizedDesTexts
IF OBJECT_ID('Custom.DenormalizedCdsTexts', 'U') IS NOT NULL DROP TABLE Custom.DenormalizedCdsTexts
GO

PRINT 'CountryDeliveries - создание'
GO

CREATE TABLE Custom.CountryDeliveries(
	TypeID int NOT NULL,
	CountryID int NOT NULL,
	ManufacturerID int NOT NULL,
	ModelID int NOT NULL
 CONSTRAINT PK_CountryDeliveries PRIMARY KEY CLUSTERED 
(
	TypeID ASC,
	CountryID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

PRINT 'CountryDeliveries - заполнение'
GO

insert into Custom.CountryDeliveries(TypeID, ManufacturerID, ModelID, CountryID)
select 
t.typ_id, mm.mfa_id, m.mod_id, c.cou_id
from dbo.tecdoc_tof_countries c
join dbo.tecdoc_tof_types t on substring(t.typ_ctm, c.cou_id + 2, 1) = 1
join dbo.tecdoc_tof_models m on m.mod_id = t.typ_mod_id
join dbo.tecdoc_tof_manufacturers mm on mm.mfa_id = m.mod_mfa_id

GO

CREATE NONCLUSTERED INDEX IDX_All ON Custom.CountryDeliveries
(
	CountryID ASC
)
INCLUDE ( TypeID,
ManufacturerID,
ModelID) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

--PRINT 'VisibleItems - создание'
--GO
--
--CREATE TABLE Custom.VisibleItems(
--	mfa_id int NOT NULL,
--	mod_id int NOT NULL,
--	typ_id int NOT NULL,
-- CONSTRAINT PK_VisibleItems PRIMARY KEY CLUSTERED 
--(
--	mfa_id ASC,
--	mod_id ASC,
--	typ_id ASC
--)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
--) ON [PRIMARY]
--GO
--
--PRINT 'VisibleItems - заполнение'
--GO
--
--insert into Custom.VisibleItems(typ_id, mod_id, mfa_id)
--select distinct
--	t.typ_id,
--	m.mod_id,
--	mm.mfa_id
--from tecdoc_tof_link_la_typ lt
--join tecdoc_tof_types t on t.typ_id = lt.lat_typ_id
--join tecdoc_tof_models m on m.mod_id = t.typ_mod_id
--join tecdoc_tof_manufacturers mm on mm.mfa_id = m.mod_mfa_id
--order by mfa_Id
--
--PRINT 'VisibleItems - тюнинх'
--GO
--CREATE NONCLUSTERED INDEX [_dta_index_VisibleItems_83_2082106458__K1] ON [Custom].[VisibleItems] 
--(
--	[mfa_id] ASC
--)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
--GO

--	sgolubev Денормализуем языковые таблицы

PRINT 'Подготавливаем индексы для денормализации языковых таблиц'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'IDX_CDS') DROP INDEX IDX_CDS ON dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS
CREATE CLUSTERED INDEX IDX_CDS ON dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS 
(
	CDS_LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'IDX_DES') DROP INDEX IDX_DES ON dbo.TECDOC_TOF_DESIGNATIONS 
CREATE CLUSTERED INDEX IDX_DES ON dbo.TECDOC_TOF_DESIGNATIONS 
(
	DES_LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Денормализуем языковые таблицы'
GO
select dsgn.des_id as [ID], max(txts.tex_text) AS [TEXT] into [Custom].[DenormalizedDesTexts]
from TECDOC_TOF_DES_TEXTS txts
join TECDOC_TOF_DESIGNATIONS dsgn on txts.TEX_ID = dsgn.DES_TEX_ID
where (dsgn.DES_LNG_ID = 16 OR dsgn.DES_LNG_ID = 255)
group by dsgn.des_id
order by dsgn.des_id

go

select cdsgn.CDS_ID as [ID], max(txts.tex_text) AS [TEXT] into [Custom].[DenormalizedCdsTexts]
from TECDOC_TOF_DES_TEXTS txts
join TECDOC_TOF_COUNTRY_DESIGNATIONS cdsgn on txts.TEX_ID = cdsgn.CDS_TEX_ID
where (cdsgn.CDS_LNG_ID = 16 OR cdsgn.CDS_LNG_ID = 255)
group by cdsgn.CDS_ID
order by cdsgn.CDS_ID

go

ALTER TABLE [Custom].[DenormalizedDesTexts] ADD CONSTRAINT PK_DenormalizedDesTexts PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE = ON, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE [Custom].[DenormalizedCdsTexts] ADD CONSTRAINT PK_DenormalizedCdsTexts PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE = ON, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

-------------------------------------------------------
-- Добавление новых названий с неверной кодировкой
-- и исправление уже известных названий на правильные
-- возможно, потребуется изменить название БД в скрипте, если оно изменится на сервере
--------------------------------------------------------

PRINT 'Добавление новых названий с неверной кодировкой'
GO
delete from ex_rmsauto_store.Tecdoc.NameCorrections
insert into ex_rmsauto_store.Tecdoc.NameCorrections(OriginalName, CorrectedName, TableName, ID)
select 
	mfa_brand, 
	mfa_brand,
	'tecdoc_tof_manufacturers',
	mfa_id
from 
	tecdoc_tof_manufacturers 
where 
	mfa_brand like '%?%'
	and lower(mfa_brand) not in (select lower(OriginalName) from ex_rmsauto_store.Tecdoc.NameCorrections)
	 
insert into ex_rmsauto_store.Tecdoc.NameCorrections(OriginalName, CorrectedName, TableName, ID)
select 
	t.text, 
	t.text,
	'tecdoc_tof_models',
	m.mod_id
from 
	tecdoc_tof_models m 
join [Custom].[DenormalizedCdsTexts] t on m.mod_cds_id = t.id
where
	t.text like '%?%'
	and lower(t.text) not in (select lower(OriginalName) from ex_rmsauto_store.Tecdoc.NameCorrections)
	
	
GO

--PRINT 'Исправление существующих названий'
--GO
--update m
--set m.mfa_brand = n.CorrectedName
--from tecdoc_tof_manufacturers m 
--join ex_rmsauto_store.Tecdoc.NameCorrections n on lower(m.mfa_brand) = lower(n.OriginalName)
--GO

--update t
--set t.text = n.CorrectedName
--from [Custom].[DenormalizedCdsTexts] t
--join tecdoc_tof_models m on m.mod_cds_id = t.id
--join ex_rmsauto_store.Tecdoc.NameCorrections n on lower(n.OriginalName) = lower(t.text)
--GO

--	sgolubev

PRINT 'Создаем праймари кей PK_TECDOC_TOF_STR_FAMILY_TREE'
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'PK_TECDOC_TOF_STR_FAMILY_TREE') ALTER TABLE
dbo.TECDOC_TOF_STR_FAMILY_TREE DROP CONSTRAINT
PK_TECDOC_TOF_STR_FAMILY_TREE
ALTER TABLE [dbo].[TECDOC_TOF_STR_FAMILY_TREE]
ADD CONSTRAINT PK_TECDOC_TOF_STR_FAMILY_TREE PRIMARY KEY CLUSTERED
(
	SFT_ANCESTOR_STR_ID ASC,
	SFT_DESCENDANT_STR_ID ASC
)
GO

--	sgolubev

PRINT 'Конвертим [dbo].[TECDOC_TOF_MANUFACTURERS].MFA_PC_MFC'
GO
ALTER TABLE [dbo].[TECDOC_TOF_MANUFACTURERS]
ALTER COLUMN MFA_PC_MFC BIT
GO

--	sgolubev

PRINT 'Конвертим [dbo].[TECDOC_TOF_MANUFACTURERS].MFA_CV_MFC'
GO
ALTER TABLE [dbo].[TECDOC_TOF_MANUFACTURERS]
ALTER COLUMN MFA_CV_MFC BIT
GO

---------------------------------------------
--GRA_DATA
---------------------------------------------

IF OBJECT_ID('dbo.TECDOC_TOF_GRA_DATA', 'U') IS NOT NULL DROP TABLE dbo.tecdoc_tof_gra_data
GO
CREATE TABLE dbo.TECDOC_TOF_GRA_DATA(
	GRD_ID int NOT NULL,
	GRD_GRAPHIC image NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_GRA1 ON dbo.TECDOC_TOF_GRA_DATA
(
	GRD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.TECDOC_TOF_GRA_DATA ADD CONSTRAINT PK_TECDOC_TOF_GRA_DATA PRIMARY KEY CLUSTERED 
(
	GRD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

PRINT 'Наполняем денормализованную таблицу GRA_DATA'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_0
GO
PRINT '0/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_1
GO
PRINT '1/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_2
GO
PRINT '2/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_3
GO
PRINT '3/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_4
GO
PRINT '4/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_5
GO
PRINT '5/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_6
GO
PRINT '6/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_7
GO
PRINT '7/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_8
GO
PRINT '8/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_9
GO
PRINT '9/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_10
GO
PRINT '10/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_11
GO
PRINT '11/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_12
GO
PRINT '12/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_13
GO
PRINT '13/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_14
GO
PRINT '14/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_15
GO
PRINT '15/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_16
GO
PRINT '16/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_17
GO
PRINT '17/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_18
GO
PRINT '18/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_19
GO
PRINT '19/20'
GO
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_20
GO
PRINT '20/20'
GO

---------------------------------------------
-- Тюнинг
---------------------------------------------

PRINT 'Тюнинги пошли'
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_ART_LOOKUP_83_1093578934__K5_K2_K1_K3_K6_K8_K9')
BEGIN
	PRINT 'Тюнинг запроса к текдоку (бренд и партнамбер) на кроссы (99% прибавки)'
	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_LOOKUP_83_1093578934__K5_K2_K1_K3_K6_K8_K9] ON [dbo].[TECDOC_TOF_ART_LOOKUP] 
	(
		[ARL_BRA_ID] ASC,
		[ARL_SEARCH_NUMBER] ASC,
		[ARL_ART_ID] ASC,
		[ARL_KIND] ASC,
		[ARL_DISPLAY_NR] ASC,
		[ARL_BLOCK] ASC,
		[ARL_SORT] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_1093578934_2_5] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_SEARCH_NUMBER], [ARL_BRA_ID])

	CREATE STATISTICS [_dta_stat_1093578934_2_1] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_SEARCH_NUMBER], [ARL_ART_ID])

	CREATE STATISTICS [_dta_stat_1093578934_6_5_2_1] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_DISPLAY_NR], [ARL_BRA_ID], [ARL_SEARCH_NUMBER], [ARL_ART_ID])

	CREATE STATISTICS [_dta_stat_1093578934_1_3_5_6_8_9] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_ART_ID], [ARL_KIND], [ARL_BRA_ID], [ARL_DISPLAY_NR], [ARL_BLOCK], [ARL_SORT])

	CREATE STATISTICS [_dta_stat_1093578934_5_1_2_3_6_8_9] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_BRA_ID], [ARL_ART_ID], [ARL_SEARCH_NUMBER], [ARL_KIND], [ARL_DISPLAY_NR], [ARL_BLOCK], [ARL_SORT])

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_BRANDS_83_1173579219__K3] ON [dbo].[TECDOC_TOF_BRANDS] 
	(
		[BRA_BRAND] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_1173579219_1_3] ON [dbo].[TECDOC_TOF_BRANDS]([BRA_ID], [BRA_BRAND])

	CREATE STATISTICS [_dta_stat_949578421_2_1] ON [dbo].[TECDOC_TOF_ARTICLES]([ART_ARTICLE_NR], [ART_ID])

	CREATE STATISTICS [_dta_stat_949578421_3_1_2] ON [dbo].[TECDOC_TOF_ARTICLES]([ART_SUP_ID], [ART_ID], [ART_ARTICLE_NR])
END
GO
IF EXISTS (SELECT 1 FROM sysindexes WHERE name =
'IX_TECDOC_TOF_ARTICLES__ARTICLE_NR_ID_SUP_ID') DROP INDEX IX_TECDOC_TOF_ARTICLES__ARTICLE_NR_ID_SUP_ID ON dbo.TECDOC_TOF_ARTICLES
CREATE INDEX IX_TECDOC_TOF_ARTICLES__ARTICLE_NR_ID_SUP_ID ON dbo.TECDOC_TOF_ARTICLES 
(
	[ART_ARTICLE_NR] ASC,
	[ART_ID] ASC,
	[ART_SUP_ID] ASC
)

GO
IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_ART_LOOKUP_83_1093578934__K2_K5_K1_K3_K6_K8_K9')
BEGIN
	PRINT 'Тюнинг запроса к текдоку (бренд не задан, партнамбер задан) на кроссы (99% прибавки)'
	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_LOOKUP_83_1093578934__K2_K5_K1_K3_K6_K8_K9] ON [dbo].[TECDOC_TOF_ART_LOOKUP] 
	(
		[ARL_SEARCH_NUMBER] ASC,
		[ARL_BRA_ID] ASC,
		[ARL_ART_ID] ASC,
		[ARL_KIND] ASC,
		[ARL_DISPLAY_NR] ASC,
		[ARL_BLOCK] ASC,
		[ARL_SORT] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ARTICLES_83_949578421__K1_K3_K2] ON [dbo].[TECDOC_TOF_ARTICLES] 
	(
		[ART_ID] ASC,
		[ART_SUP_ID] ASC,
		[ART_ARTICLE_NR] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_BRANDS_83_1173579219__K1_K3] ON [dbo].[TECDOC_TOF_BRANDS] 
	(
		[BRA_ID] ASC,
		[BRA_BRAND] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
END
GO

--	Запрос на мануфактуреров не стоит тюнить, 1-ый шаг каталога пропускаем

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_MODELS_83_114099447__K2_K6_K3_K1_4_5_7')
BEGIN
	PRINT 'Тюнинг запроса на модели мануфактурера (каталог, 2-ой шаг, 14%)'

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_MODELS_83_114099447__K2_K6_K3_K1_4_5_7] ON [dbo].[TECDOC_TOF_MODELS] 
	(
		[MOD_MFA_ID] ASC,
		[MOD_PC] ASC,
		[MOD_CDS_ID] ASC,
		[MOD_ID] ASC
	)
	INCLUDE ( [MOD_PCON_START],
	[MOD_PCON_END],
	[MOD_CV]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_114099447_6_1] ON [dbo].[TECDOC_TOF_MODELS]([MOD_PC], [MOD_ID])

	CREATE STATISTICS [_dta_stat_114099447_3_2] ON [dbo].[TECDOC_TOF_MODELS]([MOD_CDS_ID], [MOD_MFA_ID])

	CREATE STATISTICS [_dta_stat_114099447_1_3_2] ON [dbo].[TECDOC_TOF_MODELS]([MOD_ID], [MOD_CDS_ID], [MOD_MFA_ID])

	CREATE STATISTICS [_dta_stat_114099447_1_2_6] ON [dbo].[TECDOC_TOF_MODELS]([MOD_ID], [MOD_MFA_ID], [MOD_PC])

	CREATE NONCLUSTERED INDEX [_dta_index_VisibleItems_83_2082106458__K2] ON [Custom].[VisibleItems] 
	(
		[mod_id] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

END
GO

--	Запрос на модель такую то не требует тюна - пропускаем

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_TYPES_83_738101670__K4_K3_1_2_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_')
BEGIN
	PRINT 'Тюнинг запроса на модификации модели + VisibleItems (98%)'

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_TYPES_83_738101670__K4_K3_1_2_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_] ON [dbo].[TECDOC_TOF_TYPES] 
	(
		[TYP_MOD_ID] ASC,
		[TYP_MMT_CDS_ID] ASC
	)
	INCLUDE ( [TYP_ID],
	[TYP_CDS_ID],
	[TYP_SORT],
	[TYP_PCON_START],
	[TYP_PCON_END],
	[TYP_KW_FROM],
	[TYP_KW_UPTO],
	[TYP_HP_FROM],
	[TYP_HP_UPTO],
	[TYP_CCM],
	[TYP_CYLINDERS],
	[TYP_DOORS],
	[TYP_TANK],
	[TYP_KV_VOLTAGE_DES_ID],
	[TYP_KV_ABS_DES_ID],
	[TYP_KV_ASR_DES_ID],
	[TYP_KV_ENGINE_DES_ID],
	[TYP_KV_BRAKE_TYPE_DES_ID],
	[TYP_KV_BRAKE_SYST_DES_ID],
	[TYP_KV_FUEL_DES_ID],
	[TYP_KV_CATALYST_DES_ID],
	[TYP_KV_BODY_DES_ID],
	[TYP_KV_STEERING_DES_ID],
	[TYP_KV_STEERING_SIDE_DES_ID],
	[TYP_MAX_WEIGHT],
	[TYP_KV_MODEL_DES_ID],
	[TYP_KV_AXLE_DES_ID],
	[TYP_CCM_TAX],
	[TYP_LITRES],
	[TYP_KV_DRIVE_DES_ID],
	[TYP_KV_TRANS_DES_ID],
	[TYP_KV_FUEL_SUPPLY_DES_ID],
	[TYP_VALVES],
	[TYP_CTM],
	[TYP_LA_CTM]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_738101670_3_4] ON [dbo].[TECDOC_TOF_TYPES]([TYP_MMT_CDS_ID], [TYP_MOD_ID])

	CREATE STATISTICS [_dta_stat_114099447_7_1] ON [dbo].[TECDOC_TOF_MODELS]([MOD_CV], [MOD_ID])

	CREATE STATISTICS [_dta_stat_2082106458_3_2] ON [Custom].[VisibleItems]([typ_id], [mod_id])
END
GO

--	Запрос на модификацию такую то не требует тюна - пропускаем

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_LINK_LA_TYP_83_2133582639__K1_K3')
BEGIN
	PRINT 'Тюнинг запроса на детальки по дереву STR + само STR-дерево (99%)'

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_LA_TYP_83_2133582639__K1_K3] ON [dbo].[TECDOC_TOF_LINK_LA_TYP] 
	(
		[LAT_TYP_ID] ASC,
		[LAT_GA_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_2133582639_3_1] ON [dbo].[TECDOC_TOF_LINK_LA_TYP]([LAT_GA_ID], [LAT_TYP_ID])

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_GA_STR_83_1989582126__K1_K2] ON [dbo].[TECDOC_TOF_LINK_GA_STR] 
	(
		[LGS_STR_ID] ASC,
		[LGS_GA_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_SEARCH_TREE_83_306100131__K3_K1_2_4_5_6_7] ON [dbo].[TECDOC_TOF_SEARCH_TREE] 
	(
		[STR_TYPE] ASC,
		[STR_ID] ASC
	)
	INCLUDE ( [STR_ID_PARENT],
	[STR_LEVEL],
	[STR_DES_ID],
	[STR_SORT],
	[STR_NODE_NR]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_738101670_4_1] ON [dbo].[TECDOC_TOF_TYPES]([TYP_MOD_ID], [TYP_ID])
END
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_ART_LOOKUP_c_83_1093578934__K3_K1')
BEGIN
	PRINT 'Тюнинг запроса на конструкционные номера (оригиналы, 99%)'

	CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_LOOKUP_c_83_1093578934__K3_K1] ON [dbo].[TECDOC_TOF_ART_LOOKUP] 
	(
		[ARL_ART_ID] ASC,
		[ARL_KIND] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_ARTICLE_CRITERIA_c_83_981578535__K1')
BEGIN
	PRINT 'Тюнинг запроса на критерии (98%)'
	CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_ARTICLE_CRITERIA_c_83_981578535__K1] ON [dbo].[TECDOC_TOF_ARTICLE_CRITERIA] 
	(
		[ACR_ART_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_981578535_4_6] ON [dbo].[TECDOC_TOF_ARTICLE_CRITERIA]([ACR_CRI_ID], [ACR_KV_DES_ID])

	CREATE STATISTICS [_dta_stat_981578535_1_6] ON [dbo].[TECDOC_TOF_ARTICLE_CRITERIA]([ACR_ART_ID], [ACR_KV_DES_ID])

	CREATE STATISTICS [_dta_stat_981578535_4_1_6] ON [dbo].[TECDOC_TOF_ARTICLE_CRITERIA]([ACR_CRI_ID], [ACR_ART_ID], [ACR_KV_DES_ID])
END
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_LINK_LA_TYP_83_2133582639__K2_K1')
BEGIN
	PRINT 'Тюнинг запроса на дприменимость детальки к машинам'

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_LA_TYP_83_2133582639__K2_K1] ON [dbo].[TECDOC_TOF_LINK_LA_TYP] 
	(
		[LAT_LA_ID] ASC,
		[LAT_TYP_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_2133582639_1_2] ON [dbo].[TECDOC_TOF_LINK_LA_TYP]([LAT_TYP_ID], [LAT_LA_ID])

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_ART_83_1925581898__K2] ON [dbo].[TECDOC_TOF_LINK_ART] 
	(
		[LA_ART_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_1925581898_2_1] ON [dbo].[TECDOC_TOF_LINK_ART]([LA_ART_ID], [LA_ID])
END
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'[_dta_index_TECDOC_TOF_ART_COUNTRY_SPECIFICS_83_1010102639__K1_6_7]')
BEGIN
	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_COUNTRY_SPECIFICS_83_1010102639__K1_6_7] ON [dbo].[TECDOC_TOF_ART_COUNTRY_SPECIFICS] 
	(
		[ACS_ART_ID] ASC
	)
	INCLUDE ( [ACS_KV_STATUS],
	[ACS_STATUS_DATE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_COUNTRY_SPECIFICS_83_1010102639__K1_6] ON [dbo].[TECDOC_TOF_ART_COUNTRY_SPECIFICS] 
	(
		[ACS_ART_ID] ASC
	)
	INCLUDE ( [ACS_KV_STATUS]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_SUPERSEDED_ARTICLES_83_450100644__K3_K1] ON [dbo].[TECDOC_TOF_SUPERSEDED_ARTICLES] 
	(
		[SUA_NUMBER] ASC,
		[SUA_ART_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
END
GO

--	Запросы на графику, оптимизация в два захода

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_LINK_GRA_ART_83_2005582183__K1_K4_2')
BEGIN
	PRINT 'Тюнинг запроса на графику, 1-ый шаг (99%)'

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_GRA_ART_83_2005582183__K1_K4_2] ON [dbo].[TECDOC_TOF_LINK_GRA_ART] 
	(
		[LGA_ART_ID] ASC,
		[LGA_GRA_ID] ASC
	)
	INCLUDE ( [LGA_SORT]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_2005582183_4_1] ON [dbo].[TECDOC_TOF_LINK_GRA_ART]([LGA_GRA_ID], [LGA_ART_ID])

	CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_GRAPHICS_83_1493580359__K2_K3_5] ON [dbo].[TECDOC_TOF_GRAPHICS] 
	(
		[GRA_ID] ASC,
		[GRA_DOC_TYPE] ASC
	)
	INCLUDE ( [GRA_GRD_ID]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'_dta_index_TECDOC_TOF_GRAPHICS_c_83_1493580359__K5_K4')
BEGIN
	PRINT 'Тюнинг запроса на графику, 2-ой шаг (99%)'

	CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_GRAPHICS_c_83_1493580359__K5_K4] ON [dbo].[TECDOC_TOF_GRAPHICS] 
	(
		[GRA_GRD_ID] ASC,
		[GRA_LNG_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

	CREATE STATISTICS [_dta_stat_1493580359_4_5] ON [dbo].[TECDOC_TOF_GRAPHICS]([GRA_LNG_ID], [GRA_GRD_ID])
END
GO

PRINT 'Изменение типа поля в dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS'
GO
ALTER TABLE dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS
ALTER COLUMN ACS_KV_STATUS TINYINT NOT NULL
GO

PRINT 'Удаление полных дубликатов из dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS'
GO

SELECT DISTINCT *
INTO #TMP
FROM dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS
GO
DELETE dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS
GO
INSERT dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS
SELECT * FROM #TMP
GO
DROP TABLE #TMP
GO

PRINT 'Создадим индекс и тюненую статистику на dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS'
GO

IF NOT EXISTS (SELECT 1 FROM sysindexes WHERE name =
'IX_TECDOC_TOF_ART_COUNTRY_SPECIFICS')
BEGIN
	CREATE CLUSTERED INDEX IX_TECDOC_TOF_ART_COUNTRY_SPECIFICS ON [dbo].[TECDOC_TOF_ART_COUNTRY_SPECIFICS] 
	(
		[ACS_ART_ID] ASC
	)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
END
ELSE
	BEGIN		
		PRINT 'Ключик IX_TECDOC_TOF_ART_COUNTRY_SPECIFICS уже есть'
	END
GO

IF NOT EXISTS (SELECT * FROM sys.stats 
           WHERE object_id = object_id('dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS')
           AND name = '_dta_stat_1010102639_5_1')
BEGIN
	CREATE STATISTICS [_dta_stat_1010102639_5_1] ON [dbo].[TECDOC_TOF_ART_COUNTRY_SPECIFICS]([ACS_KV_STATUS_DES_ID], [ACS_ART_ID])
END
ELSE
	BEGIN		
		PRINT 'Тюненая статистика _dta_stat_1010102639_5_1 уже есть'
	END

GO

--PRINT 'Создадим процедуру по поиску цепочки замен'
--GO

--	почему то CREATE PROCEDURE не хочет быть в IF %-0. Индусы?

--CREATE PROCEDURE [dbo].[GetSupersededChain]
--	@ArticleNumber varchar(66),
--	@ArticleId int
--AS
--	BEGIN
--		WITH SuperS (NumberFrom, ArtIDFrom, ArtNumberTo, ArtIDTo)
--		AS
--		(
--		WITH SuperS (NumberFrom, ArtIDFrom, ArtNumberTo, ArtIDTo, Mfr)
--		AS
--		(
--			SELECT 
--				  s.sua_number, @ArticleId, a.art_article_nr, a.art_id, sp.sup_brand
--			FROM 
--				  TECDOC_TOF_SUPERSEDED_ARTICLES s
--						INNER JOIN TECDOC_TOF_ARTICLES a on s.sua_art_id = a.art_id
--						INNER JOIN dbo.TECDOC_TOF_SUPPLIERS sp ON sp.sup_id = a.art_sup_id
--				   WHERE sua_number = @ArticleNumber 
--			UNION ALL
--			SELECT 
--				  s.sua_number, ss.ArtIDTo, a.art_article_nr, a.art_id, sp.sup_brand
--			FROM
--				  TECDOC_TOF_SUPERSEDED_ARTICLES s
--						inner join TECDOC_TOF_ARTICLES a on s.sua_art_id = a.art_id
--						INNER JOIN dbo.TECDOC_TOF_SUPPLIERS sp ON sp.sup_id = a.art_sup_id
--						inner join SuperS ss on ss.ArtNumberTo = s.sua_number 
--		)
--
--		SELECT
--			s.NumberFrom as NumberFrom,
--			acs1.ACS_KV_STATUS as StatusFrom,
--			s.ArtNumberTo as NumberTo,
--			acs2.ACS_KV_STATUS as StatusTo,
--			acs1.ACS_STATUS_DATE as StatusDate,
--			s.Mfr as Mfr
--		from SuperS s
--		INNER JOIN dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS acs1 on acs1.acs_art_id = s.ArtIDFrom
--		INNER JOIN dbo.TECDOC_TOF_ART_COUNTRY_SPECIFICS acs2 on acs2.acs_art_id = s.ArtIDTo	END

