--USE ex_tecdocs
--GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF OBJECT_ID('dbo.TECDOC_TOF_GRA_DATA', 'U') IS NOT NULL DROP TABLE dbo.tecdoc_tof_gra_data
GO
CREATE TABLE dbo.TECDOC_TOF_GRA_DATA(
	GRD_ID int NOT NULL,
	GRD_GRAPHIC image NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO




CREATE NONCLUSTERED INDEX idx_GRA1 ON dbo.TECDOC_TOF_GRA_DATA
(
	GRD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_GRA_DATA ADD  CONSTRAINT PK_TECDOC_TOF_GRA_DATA PRIMARY KEY CLUSTERED 
(
	GRD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_0
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_1
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_2
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_3
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_4
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_5
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_6
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_7
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_8
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_9
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_10
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_11
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_12
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_13
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_14
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_15
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_16
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_17
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_18
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_19
insert into dbo.tecdoc_tof_gra_data
select * from tecdoc_tof_gra_data_20

GO

CREATE NONCLUSTERED INDEX IX_ART_ID_SEARCH_NUMBER ON dbo.TECDOC_TOF_ART_LOOKUP 
(
	ARL_ART_ID ASC,
	ARL_SEARCH_NUMBER ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_TECDOC_TOF_ART_LOOKUP ON dbo.TECDOC_TOF_ART_LOOKUP 
(
	ARL_ART_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_TECDOC_TOF_ART_LOOKUP_1 ON dbo.TECDOC_TOF_ART_LOOKUP 
(
	ARL_SEARCH_NUMBER ASC,
	ARL_BRA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_ACR1 ON dbo.TECDOC_TOF_ARTICLE_CRITERIA 
(
	ACR_CRI_ID ASC,
	ACR_KV_DES_ID ASC,
	ACR_ART_ID ASC,
	ACR_SORT ASC,
	ACR_VALUE ASC,
	ACR_DISPLAY ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX idx_ACR2 ON dbo.TECDOC_TOF_ARTICLE_CRITERIA 
(
	ACR_ART_ID ASC,
	ACR_CRI_ID ASC,
	ACR_KV_DES_ID ASC,
	ACR_SORT ASC,
	ACR_VALUE ASC,
	ACR_DISPLAY ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_ART1 ON dbo.TECDOC_TOF_ARTICLES 
(
	ART_ID ASC,
	ART_SUP_ID ASC,
	ART_COMPLETE_DES_ID ASC,
	ART_DES_ID ASC
)
INCLUDE ( ART_ARTICLE_NR) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_ARTICLES ADD  CONSTRAINT PK_TECDOC_TOF_ARTICLES PRIMARY KEY CLUSTERED 
(
	ART_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_TECDOC_TOF_BRANDS ON dbo.TECDOC_TOF_BRANDS 
(
	BRA_MF_NR ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_BRANDS ADD  CONSTRAINT PK_TECDOC_TOF_BRANDS PRIMARY KEY CLUSTERED 
(
	BRA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_COUNTRIES ADD  CONSTRAINT PK_TECDOC_TOF_COUNTRIES PRIMARY KEY CLUSTERED 
(
	COU_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO


CREATE NONCLUSTERED INDEX idx_CDS1 ON dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS 
(
	CDS_LNG_ID ASC,
	CDS_ID ASC,
	CDS_TEX_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_CDS2 ON dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS
(
	CDS_LNG_ID ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX idx_CDS2 ON dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS 
(
	CDS_ID ASC,
	CDS_LNG_ID ASC,
	CDS_TEX_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_CRITERIA ADD  CONSTRAINT PK_TECDOC_TOF_CRITERIA PRIMARY KEY CLUSTERED 
(
	CRI_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_DES_TEXTS ADD  CONSTRAINT PK_TECDOC_TOF_DES_TEXTS PRIMARY KEY CLUSTERED 
(
	TEX_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_DES1 ON dbo.TECDOC_TOF_DESIGNATIONS 
(
	DES_LNG_ID ASC,
	DES_ID ASC,
	DES_TEX_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX idx_DES2 ON dbo.TECDOC_TOF_DESIGNATIONS 
(
	DES_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_DOC_TYPES ADD  CONSTRAINT PK_TECDOC_TOF_DOC_TYPES PRIMARY KEY CLUSTERED 
(
	DOC_TYPE ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_ENGINES ADD  CONSTRAINT PK_TECDOC_TOF_ENGINES PRIMARY KEY CLUSTERED 
(
	ENG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_GA1 ON dbo.TECDOC_TOF_GENERIC_ARTICLES 
(
	GA_ID ASC
)
INCLUDE ( GA_DES_ID,
GA_DES_ID_STANDARD,
GA_DES_ID_ASSEMBLY,
GA_DES_ID_INTENDED) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_GENERIC_ARTICLES ADD  CONSTRAINT PK_TECDOC_TOF_GENERIC_ARTICLES PRIMARY KEY CLUSTERED 
(
	GA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_GRA1 ON dbo.TECDOC_TOF_GRAPHICS 
(
	GRA_ID ASC,
	GRA_GRD_ID ASC,
	GRA_DOC_TYPE ASC,
	GRA_SUP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_LANGUAGES ADD  CONSTRAINT PK_TECDOC_TOF_LANGUAGES PRIMARY KEY CLUSTERED 
(
	LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_LA1 ON dbo.TECDOC_TOF_LINK_ART 
(
	LA_ART_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_LINK_ART ADD  CONSTRAINT PK_LA_ID PRIMARY KEY CLUSTERED 
(
	LA_ID ASC
)WITH (PAD_INDEX  = ON, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_LAG ON dbo.TECDOC_TOF_LINK_ART_GA 
(
	LAG_ART_ID ASC,
	LAG_GA_ID ASC,
	LAG_SUP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_LGS1 ON dbo.TECDOC_TOF_LINK_GA_STR 
(
	LGS_STR_ID ASC,
	LGS_GA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_LGA1 ON dbo.TECDOC_TOF_LINK_GRA_ART 
(
	LGA_ART_ID ASC
)
INCLUDE ( LGA_GRA_ID) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_LAT1 ON dbo.TECDOC_TOF_LINK_LA_TYP 
(
	LAT_TYP_ID ASC,
	LAT_GA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_LAT2 ON dbo.TECDOC_TOF_LINK_LA_TYP 
(
	LAT_LA_ID ASC,
	LAT_GA_ID ASC,
	LAT_TYP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS ADD  CONSTRAINT PK_TECDOC_TOF_MANUFACTURERS PRIMARY KEY CLUSTERED 
(
	MFA_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_MOD1 ON dbo.TECDOC_TOF_MODELS 
(
	MOD_MFA_ID ASC,
	MOD_ID ASC,
	MOD_CDS_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_MOD2 ON dbo.TECDOC_TOF_MODELS 
(
	MOD_ID ASC,
	MOD_PC ASC,
	MOD_CV ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_MOD3 ON dbo.TECDOC_TOF_MODELS 
(
	MOD_ID ASC,
	MOD_MFA_ID ASC,
	MOD_CDS_ID ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_MODELS ADD  CONSTRAINT PK_TECDOC_TOF_MODELS PRIMARY KEY CLUSTERED 
(
	MOD_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_TECDOC_TOF_SEARCH_TREE ON dbo.TECDOC_TOF_SEARCH_TREE 
(
	STR_ID ASC,
	STR_ID_PARENT ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_SEARCH_TREE ADD  CONSTRAINT PK_TECDOC_TOF_SEARCH_TREE PRIMARY KEY CLUSTERED 
(
	STR_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_STL1 ON dbo.TECDOC_TOF_STR_LOOKUP 
(
	STL_GA_ID ASC,
	STL_STR_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULE_TEXTS ADD  CONSTRAINT PK_TECDOC_TOF_TEXT_MODULE_TEXTS PRIMARY KEY CLUSTERED 
(
	TMT_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES ADD  CONSTRAINT PK_TECDOC_TOF_TEXT_MODULES PRIMARY KEY CLUSTERED 
(
	TMO_ID ASC,
	TMO_LNG_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_TYP1 ON dbo.TECDOC_TOF_TYPES 
(
	TYP_KV_ASR_DES_ID ASC,
	TYP_MOD_ID ASC,
	TYP_ID ASC,
	TYP_KV_FUEL_SUPPLY_DES_ID ASC,
	TYP_KV_TRANS_DES_ID ASC,
	TYP_KV_DRIVE_DES_ID ASC,
	TYP_KV_AXLE_DES_ID ASC,
	TYP_KV_MODEL_DES_ID ASC,
	TYP_KV_STEERING_SIDE_DES_ID ASC,
	TYP_CDS_ID ASC,
	TYP_KV_STEERING_DES_ID ASC,
	TYP_KV_BODY_DES_ID ASC,
	TYP_KV_CATALYST_DES_ID ASC,
	TYP_KV_FUEL_DES_ID ASC,
	TYP_KV_BRAKE_SYST_DES_ID ASC,
	TYP_KV_BRAKE_TYPE_DES_ID ASC
)
INCLUDE ( TYP_MMT_CDS_ID,
TYP_SORT,
TYP_PCON_START,
TYP_PCON_END,
TYP_KW_FROM,
TYP_KW_UPTO,
TYP_HP_FROM,
TYP_HP_UPTO,
TYP_CCM,
TYP_CYLINDERS,
TYP_DOORS,
TYP_TANK,
TYP_KV_ABS_DES_ID,
TYP_KV_ENGINE_DES_ID,
TYP_MAX_WEIGHT,
TYP_CCM_TAX,
TYP_LITRES,
TYP_VALVES,
TYP_RT_EXISTS) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX idx_TYP2 ON dbo.TECDOC_TOF_TYPES 
(
	TYP_MOD_ID ASC,
	TYP_ID ASC,
	TYP_CDS_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE dbo.TECDOC_TOF_TYPES ADD  CONSTRAINT PK_TECDOC_TOF_TYPES PRIMARY KEY CLUSTERED 
(
	TYP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX idx_TYP3 ON dbo.TECDOC_TOF_TYPES 
(
	TYP_ID ASC,
	TYP_MOD_ID ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO

ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS ADD  CONSTRAINT PK_TECDOC_TOF_SUPPLIERS PRIMARY KEY CLUSTERED 
(
	SUP_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


IF OBJECT_ID('dbo.spSearchPartsByArticleID', 'P') IS NOT NULL drop procedure dbo.spSearchPartsByArticleID
GO

create procedure dbo.spSearchPartsByArticleID(@ArticleID int, @BrandID int)
as

declare 
	@artNumber varchar(50),
	@brand varchar(60)
		
select @brand = bra_brand from tecdoc_tof_brands
where
	bra_id = @BrandID
	
select 
	@artNumber  = art_article_nr 
from  
	v_art_articles
where 
	art_id = @ArticleID 
	and sup_brand = @Brand

SELECT 
	@artNumber as SearchPartNumber,   
	s.SUP_BRAND as Brand, 
	al.ARL_DISPLAY_NR as PartNumber
FROM         
	TECDOC_TOF_BRANDS b RIGHT OUTER JOIN TECDOC_TOF_SUPPLIERS s
	INNER JOIN TECDOC_TOF_ARTICLES a ON s.SUP_ID = a.ART_SUP_ID 
	INNER JOIN TECDOC_TOF_ART_LOOKUP al ON a.ART_ID = al.ARL_ART_ID ON b.BRA_ID = al.ARL_BRA_ID
where 
	arl_search_number = @artNumber
	and al.arl_display_nr is not null
order by 1, 2
GO

IF OBJECT_ID('dbo.fArticleAddInfo', 'FN') IS NOT NULL drop function dbo.fArticleAddInfo
GO

create function dbo.fArticleAddInfo(@ArticleID int) 
returns varchar(4000) with schemabinding
as
begin
	declare @output varchar(4000)

set @output =
(
		select
			c.cri_text + ': ' + 
			case 
				when c.acr_value is null
				then c.acr_kv_text
				else c.acr_value
			end + '<br/>'
		 from dbo.v_art_article_criteria c
		where 
			c.acr_art_id = @ArticleID
		for xml path('')
)
return replace(replace(@output, '&lt;', '<'), '&gt;', '>')
end




--------------------------------------------
--FK
---------------------------------------------

SET ANSI_PADDING OFF
GO
ALTER TABLE dbo.TECDOC_TOF_ART_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_ARTICLES FOREIGN KEY(ARL_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ART_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_ART_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_BRANDS FOREIGN KEY(ARL_BRA_ID)
REFERENCES dbo.TECDOC_TOF_BRANDS (BRA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ART_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_ART_LOOKUP_TECDOC_TOF_BRANDS
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_INFO  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_ARTICLES FOREIGN KEY(AIN_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_INFO CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_INFO  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(AIN_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_INFO CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_INFO_TECDOC_TOF_GENERIC_ARTICLES
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ARTICLES FOREIGN KEY(ALC_ALI_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_CRITERIA FOREIGN KEY(ALC_CRI_ID)
REFERENCES dbo.TECDOC_TOF_CRITERIA (CRI_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_CRITERIA
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ENGINES FOREIGN KEY(ALC_ENG_ID)
REFERENCES dbo.TECDOC_TOF_ENGINES (ENG_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_ENGINES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_TYPES FOREIGN KEY(ALC_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LIST_CRITERIA CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LIST_CRITERIA_TECDOC_TOF_TYPES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES FOREIGN KEY(ALI_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES1 FOREIGN KEY(ALI_ART_ID_COMPONENT)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_ARTICLES1
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(ALI_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLE_LISTS CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLE_LISTS_TECDOC_TOF_GENERIC_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ARTICLES_TECDOC_TOF_SUPPLIERS FOREIGN KEY(ART_SUP_ID)
REFERENCES dbo.TECDOC_TOF_SUPPLIERS (SUP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ARTICLES CHECK CONSTRAINT FK_TECDOC_TOF_ARTICLES_TECDOC_TOF_SUPPLIERS
GO
ALTER TABLE dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_DES_TEXTS FOREIGN KEY(CDS_TEX_ID)
REFERENCES dbo.TECDOC_TOF_DES_TEXTS (TEX_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS CHECK CONSTRAINT FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_DES_TEXTS
GO
ALTER TABLE dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_LANGUAGES FOREIGN KEY(CDS_LNG_ID)
REFERENCES dbo.TECDOC_TOF_LANGUAGES (LNG_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS CHECK CONSTRAINT FK_TECDOC_TOF_COUNTRY_DESIGNATIONS_TECDOC_TOF_LANGUAGES
GO
ALTER TABLE dbo.TECDOC_TOF_DESIGNATIONS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_DESIGNATIONS_TECDOC_TOF_DES_TEXTS FOREIGN KEY(DES_TEX_ID)
REFERENCES dbo.TECDOC_TOF_DES_TEXTS (TEX_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_DESIGNATIONS CHECK CONSTRAINT FK_TECDOC_TOF_DESIGNATIONS_TECDOC_TOF_DES_TEXTS
GO
ALTER TABLE dbo.TECDOC_TOF_ENGINES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_ENGINES_TECDOC_TOF_MANUFACTURERS FOREIGN KEY(ENG_MFA_ID)
REFERENCES dbo.TECDOC_TOF_MANUFACTURERS (MFA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_ENGINES CHECK CONSTRAINT FK_TECDOC_TOF_ENGINES_TECDOC_TOF_MANUFACTURERS
GO
ALTER TABLE dbo.TECDOC_TOF_GRAPHICS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_GRAPHICS_TECDOC_TOF_DOC_TYPES FOREIGN KEY(GRA_DOC_TYPE)
REFERENCES dbo.TECDOC_TOF_DOC_TYPES (DOC_TYPE)
GO
ALTER TABLE dbo.TECDOC_TOF_GRAPHICS CHECK CONSTRAINT FK_TECDOC_TOF_GRAPHICS_TECDOC_TOF_DOC_TYPES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_ARTICLES FOREIGN KEY(LA_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART CHECK CONSTRAINT FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(LA_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART CHECK CONSTRAINT FK_TECDOC_TOF_LINK_ART_TECDOC_TOF_GENERIC_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_ARTICLES FOREIGN KEY(LAG_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA CHECK CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(LAG_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA CHECK CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_GENERIC_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_SUPPLIERS FOREIGN KEY(LAG_SUP_ID)
REFERENCES dbo.TECDOC_TOF_SUPPLIERS (SUP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_ART_GA CHECK CONSTRAINT FK_TECDOC_TOF_LINK_ART_GA_TECDOC_TOF_SUPPLIERS
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GA_STR  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(LGS_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GA_STR CHECK CONSTRAINT FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_GENERIC_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GA_STR  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_SEARCH_TREE FOREIGN KEY(LGS_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GA_STR CHECK CONSTRAINT FK_TECDOC_TOF_LINK_GA_STR_TECDOC_TOF_SEARCH_TREE
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_ART  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_GRA_ART_TECDOC_TOF_ARTICLES FOREIGN KEY(LGA_ART_ID)
REFERENCES dbo.TECDOC_TOF_ARTICLES (ART_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_ART CHECK CONSTRAINT FK_TECDOC_TOF_LINK_GRA_ART_TECDOC_TOF_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_LA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_LINK_ART FOREIGN KEY(LGL_LA_ID)
REFERENCES dbo.TECDOC_TOF_LINK_ART (LA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_LA CHECK CONSTRAINT FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_LINK_ART
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_LA  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_TYPES FOREIGN KEY(LGL_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_GRA_LA CHECK CONSTRAINT FK_TECDOC_TOF_LINK_GRA_LA_TECDOC_TOF_TYPES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_GENERIC_ARTICLES FOREIGN KEY(LAT_GA_ID)
REFERENCES dbo.TECDOC_TOF_GENERIC_ARTICLES (GA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP CHECK CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_GENERIC_ARTICLES
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_LINK_ART FOREIGN KEY(LAT_LA_ID)
REFERENCES dbo.TECDOC_TOF_LINK_ART (LA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP CHECK CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_LINK_ART
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_SUPPLIERS FOREIGN KEY(LAT_SUP_ID)
REFERENCES dbo.TECDOC_TOF_SUPPLIERS (SUP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP CHECK CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_SUPPLIERS
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES FOREIGN KEY(LAT_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_LINK_LA_TYP CHECK CONSTRAINT FK_TECDOC_TOF_LINK_LA_TYP_TECDOC_TOF_TYPES
GO
ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS FOREIGN KEY(MFA_MF_NR)
REFERENCES dbo.TECDOC_TOF_BRANDS (BRA_MF_NR)
GO
ALTER TABLE dbo.TECDOC_TOF_MANUFACTURERS CHECK CONSTRAINT FK_TECDOC_TOF_MANUFACTURERS_TECDOC_TOF_BRANDS
GO
ALTER TABLE dbo.TECDOC_TOF_MOD_TYP_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES FOREIGN KEY(MTL_TYP_ID)
REFERENCES dbo.TECDOC_TOF_TYPES (TYP_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_MOD_TYP_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_MOD_TYP_LOOKUP_TECDOC_TOF_TYPES
GO
ALTER TABLE dbo.TECDOC_TOF_MODELS  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS FOREIGN KEY(MOD_MFA_ID)
REFERENCES dbo.TECDOC_TOF_MANUFACTURERS (MFA_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_MODELS CHECK CONSTRAINT FK_TECDOC_TOF_MODELS_TECDOC_TOF_MANUFACTURERS
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE FOREIGN KEY(SFT_ANCESTOR_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE CHECK CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1 FOREIGN KEY(SFT_DESCENDANT_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_FAMILY_TREE CHECK CONSTRAINT FK_TECDOC_TOF_STR_FAMILY_TREE_TECDOC_TOF_SEARCH_TREE1
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES FOREIGN KEY(STL_LNG_ID)
REFERENCES dbo.TECDOC_TOF_LANGUAGES (LNG_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_LANGUAGES
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE FOREIGN KEY(STL_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1 FOREIGN KEY(STL_STR_ID)
REFERENCES dbo.TECDOC_TOF_SEARCH_TREE (STR_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_STR_LOOKUP CHECK CONSTRAINT FK_TECDOC_TOF_STR_LOOKUP_TECDOC_TOF_SEARCH_TREE1
GO
ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS FOREIGN KEY(TMO_TMT_ID)
REFERENCES dbo.TECDOC_TOF_TEXT_MODULE_TEXTS (TMT_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_TEXT_MODULES CHECK CONSTRAINT FK_TECDOC_TOF_TEXT_MODULES_TECDOC_TOF_TEXT_MODULE_TEXTS
GO
ALTER TABLE dbo.TECDOC_TOF_TYPES  WITH CHECK ADD  CONSTRAINT FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS FOREIGN KEY(TYP_MOD_ID)
REFERENCES dbo.TECDOC_TOF_MODELS (MOD_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_TYPES CHECK CONSTRAINT FK_TECDOC_TOF_TYPES_TECDOC_TOF_MODELS
GO
ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS  WITH NOCHECK ADD  CONSTRAINT FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES FOREIGN KEY(SUP_COU_ID)
REFERENCES dbo.TECDOC_TOF_COUNTRIES (COU_ID)
GO
ALTER TABLE dbo.TECDOC_TOF_SUPPLIERS NOCHECK CONSTRAINT FK_TECDOC_TOF_SUPPLIERS_TECDOC_TOF_COUNTRIES 


GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.v_art_article_criteria with schemabinding
AS
SELECT DISTINCT 
                      dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_ART_ID, dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_SORT, v_des_texts_2.TEX_TEXT AS CRI_TEXT, 
                      v_des_texts_1.TEX_TEXT AS CRI_SHORT_TEXT, v_des_texts_3.TEX_TEXT AS CRI_UNIT_TEXT, dbo.TECDOC_TOF_CRITERIA.CRI_TYPE, 
                      dbo.TECDOC_TOF_CRITERIA.CRI_KT_ID, dbo.TECDOC_TOF_CRITERIA.CRI_IS_INTERVAL, dbo.TECDOC_TOF_CRITERIA.CRI_SUCCESSOR, 
                      dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_VALUE, dbo.v_des_texts.TEX_TEXT AS ACR_KV_TEXT, 
                      dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_DISPLAY
FROM         dbo.v_des_texts RIGHT OUTER JOIN
                      dbo.TECDOC_TOF_ARTICLE_CRITERIA INNER JOIN
                      dbo.TECDOC_TOF_CRITERIA ON dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_CRI_ID = dbo.TECDOC_TOF_CRITERIA.CRI_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_CRITERIA.CRI_UNIT_DES_ID = v_des_texts_3.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_CRITERIA.CRI_SHORT_DES_ID = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_CRITERIA.CRI_DES_ID = v_des_texts_2.DES_ID ON 
                      dbo.v_des_texts.DES_ID = dbo.TECDOC_TOF_ARTICLE_CRITERIA.ACR_KV_DES_ID



GO

CREATE VIEW dbo.v_art_articles
WITH SCHEMABINDING 
AS
SELECT     dbo.TECDOC_TOF_ARTICLES.ART_ID, dbo.TECDOC_TOF_ARTICLES.ART_SUP_ID,dbo.TECDOC_TOF_ARTICLES.ART_ARTICLE_NR, dbo.TECDOC_TOF_SUPPLIERS.SUP_BRAND, 
                      dbo.v_des_texts.TEX_TEXT AS ART_TEXT, v_des_texts_1.TEX_TEXT AS ART_COMPLETE_TEXT, 
                      dbo.TECDOC_TOF_ARTICLES.ART_PACK_SELFSERVICE, dbo.TECDOC_TOF_ARTICLES.ART_MATERIAL_MARK, 
                      dbo.TECDOC_TOF_ARTICLES.ART_REPLACEMENT, dbo.TECDOC_TOF_ARTICLES.ART_ACCESSORY, dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE1, 
                      dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE2
FROM         dbo.TECDOC_TOF_ARTICLES LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_ARTICLES.ART_COMPLETE_DES_ID = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_ARTICLES.ART_DES_ID = dbo.v_des_texts.DES_ID LEFT OUTER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON dbo.TECDOC_TOF_ARTICLES.ART_SUP_ID = dbo.TECDOC_TOF_SUPPLIERS.SUP_ID


GO

CREATE VIEW dbo.v_art_graphics 
AS
SELECT     TECDOC_TOF_LINK_GRA_ART.LGA_ART_ID, TECDOC_TOF_LINK_GRA_ART.LGA_SORT, TECDOC_TOF_SUPPLIERS.SUP_BRAND, 
                      TECDOC_TOF_DOC_TYPES.DOC_EXTENSION, TECDOC_TOF_GRAPHICS.GRA_LNG_ID, TECDOC_TOF_GRAPHICS.GRA_TYPE, 
                      TECDOC_TOF_GRAPHICS.GRA_NORM, TECDOC_TOF_GRAPHICS.GRA_TAB_NR, v_des_texts.TEX_TEXT AS GRA_DESIGNATION, 
                      TECDOC_TOF_GRA_DATA.GRD_ID, TECDOC_TOF_GRA_DATA.GRD_GRAPHIC
FROM         dbo.TECDOC_TOF_LINK_GRA_ART INNER JOIN
                      dbo.TECDOC_TOF_GRAPHICS ON TECDOC_TOF_LINK_GRA_ART.LGA_GRA_ID = TECDOC_TOF_GRAPHICS.GRA_ID INNER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON TECDOC_TOF_GRAPHICS.GRA_SUP_ID = TECDOC_TOF_SUPPLIERS.SUP_ID INNER JOIN
                      dbo.TECDOC_TOF_DOC_TYPES ON TECDOC_TOF_GRAPHICS.GRA_DOC_TYPE = TECDOC_TOF_DOC_TYPES.DOC_TYPE INNER JOIN
                      dbo.TECDOC_TOF_GRA_DATA ON TECDOC_TOF_GRAPHICS.GRA_GRD_ID = TECDOC_TOF_GRA_DATA.GRD_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON TECDOC_TOF_GRAPHICS.GRA_DES_ID = v_des_texts.DES_ID


GO


CREATE VIEW dbo.v_art_lookup
AS
SELECT     dbo.TECDOC_TOF_ART_LOOKUP.ARL_ART_ID, dbo.TECDOC_TOF_ART_LOOKUP.ARL_KIND, dbo.TECDOC_TOF_BRANDS.BRA_BRAND, 
                      dbo.TECDOC_TOF_ART_LOOKUP.ARL_DISPLAY_NR
FROM         dbo.TECDOC_TOF_ART_LOOKUP LEFT OUTER JOIN
                      dbo.TECDOC_TOF_BRANDS ON dbo.TECDOC_TOF_ART_LOOKUP.ARL_BRA_ID = dbo.TECDOC_TOF_BRANDS.BRA_ID




GO

CREATE VIEW dbo.v_art_typ
AS
SELECT DISTINCT 
                      dbo.TECDOC_TOF_LINK_ART.LA_ART_ID, dbo.v_typ_types.TYP_ID, dbo.v_typ_types.TYP_TEXT, dbo.v_typ_types.TYP_MMT_TEXT, 
                      dbo.v_typ_types.TYP_MOD_ID, dbo.v_typ_types.MOD_PC, dbo.v_typ_types.MOD_CV, dbo.v_typ_types.TYP_SORT, 
                      dbo.v_typ_types.TYP_PCON_START, dbo.v_typ_types.TYP_PCON_END, dbo.v_typ_types.TYP_KW_FROM, dbo.v_typ_types.TYP_KW_UPTO, 
                      dbo.v_typ_types.TYP_HP_FROM, dbo.v_typ_types.TYP_HP_UPTO, dbo.v_typ_types.TYP_CCM, dbo.v_typ_types.TYP_CYLINDERS, 
                      dbo.v_typ_types.TYP_DOORS, dbo.v_typ_types.TYP_TANK, dbo.v_typ_types.KV_ABS_TEXT, dbo.v_typ_types.KV_ASR_TEXT, 
                      dbo.v_typ_types.KV_ENGINE_TEXT, dbo.v_typ_types.KV_BRAKE_TYPE_TEXT, dbo.v_typ_types.KV_BRAKE_SYST_TEXT, 
                      dbo.v_typ_types.KV_FUEL_TEXT, dbo.v_typ_types.KV_CATALYST_TEXT, dbo.v_typ_types.KV_BODY_TEXT, dbo.v_typ_types.KV_STEERING_TEXT, 
                      dbo.v_typ_types.KV_STEERING_SIDE_TEXT, dbo.v_typ_types.TYP_MAX_WEIGHT, dbo.v_typ_types.KV_MODEL_TEXT, 
                      dbo.v_typ_types.KV_AXLE_TEXT, dbo.v_typ_types.TYP_CCM_TAX, dbo.v_typ_types.TYP_LITRES, dbo.v_typ_types.KV_DRIVE_TEXT, 
                      dbo.v_typ_types.KV_TRANS_TEXT, dbo.v_typ_types.KV_FUEL_SUPPLY_TEXT, dbo.v_typ_types.TYP_VALVES, 
                      dbo.v_typ_types.TYP_RT_EXISTS
FROM         dbo.TECDOC_TOF_LINK_LA_TYP INNER JOIN
                      dbo.TECDOC_TOF_LINK_ART ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_LA_ID = dbo.TECDOC_TOF_LINK_ART.LA_ID INNER JOIN
                      dbo.v_typ_types ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_TYP_ID = dbo.v_typ_types.TYP_ID



GO

CREATE VIEW dbo.v_cds_texts
WITH SCHEMABINDING 
AS
SELECT     dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS.CDS_ID, MAX(DISTINCT dbo.TECDOC_TOF_DES_TEXTS.TEX_TEXT) AS TEX_TEXT
FROM         dbo.TECDOC_TOF_DES_TEXTS INNER JOIN
                      dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS ON 
                      dbo.TECDOC_TOF_DES_TEXTS.TEX_ID = dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS.CDS_TEX_ID
WHERE     (dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS.CDS_LNG_ID = 16) OR
                      (dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS.CDS_LNG_ID = 255)
GROUP BY dbo.TECDOC_TOF_COUNTRY_DESIGNATIONS.CDS_ID


GO

CREATE VIEW dbo.v_des_texts
WITH SCHEMABINDING 
AS
SELECT     dbo.TECDOC_TOF_DESIGNATIONS.DES_ID, MAX(DISTINCT dbo.TECDOC_TOF_DES_TEXTS.TEX_TEXT) AS TEX_TEXT
FROM         dbo.TECDOC_TOF_DESIGNATIONS INNER JOIN
                      dbo.TECDOC_TOF_DES_TEXTS ON dbo.TECDOC_TOF_DESIGNATIONS.DES_TEX_ID = dbo.TECDOC_TOF_DES_TEXTS.TEX_ID
WHERE     (dbo.TECDOC_TOF_DESIGNATIONS.DES_LNG_ID = 16) OR
                      (dbo.TECDOC_TOF_DESIGNATIONS.DES_LNG_ID = 255)
GROUP BY dbo.TECDOC_TOF_DESIGNATIONS.DES_ID



GO

CREATE VIEW dbo.v_ga_generic_articles with schemabinding
AS
SELECT     dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_ID, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_NR, dbo.v_des_texts.TEX_TEXT AS GA_TEXT, 
                      v_des_texts_1.TEX_TEXT AS GA_STANDART_TEXT, v_des_texts_2.TEX_TEXT AS GA_ASSEMBLY_TEXT, 
                      v_des_texts_3.TEX_TEXT AS GA_INTENDED_TEXT, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_UNIVERSAL
FROM         dbo.TECDOC_TOF_GENERIC_ARTICLES LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_INTENDED = v_des_texts_3.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_ASSEMBLY = v_des_texts_2.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_STANDARD = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID = dbo.v_des_texts.DES_ID




GO

CREATE VIEW dbo.v_grd_data
AS
SELECT     GRD_ID, GRD_GRAPHIC
FROM         dbo.TECDOC_TOF_GRA_DATA



GO

CREATE VIEW dbo.v_link_typ_str
WITH SCHEMABINDING
AS
SELECT DISTINCT 
                      dbo.TECDOC_TOF_LINK_LA_TYP.LAT_TYP_ID, dbo.TECDOC_TOF_SEARCH_TREE.STR_ID, dbo.TECDOC_TOF_SEARCH_TREE.STR_ID_PARENT, 
                      dbo.TECDOC_TOF_SEARCH_TREE.STR_TYPE, dbo.TECDOC_TOF_SEARCH_TREE.STR_LEVEL, dbo.v_des_texts.TEX_TEXT AS STR_TEXT, 
                      dbo.TECDOC_TOF_SEARCH_TREE.STR_SORT, dbo.TECDOC_TOF_SEARCH_TREE.STR_NODE_NR
FROM         dbo.TECDOC_TOF_LINK_LA_TYP INNER JOIN
                      dbo.TECDOC_TOF_LINK_GA_STR ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_LINK_GA_STR.LGS_GA_ID INNER JOIN
                      dbo.TECDOC_TOF_SEARCH_TREE ON dbo.TECDOC_TOF_LINK_GA_STR.LGS_STR_ID = dbo.TECDOC_TOF_SEARCH_TREE.STR_ID INNER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_SEARCH_TREE.STR_DES_ID = dbo.v_des_texts.DES_ID





GO

CREATE VIEW dbo.v_link_typ_str_art_ga
WITH SCHEMABINDING 
AS
SELECT DISTINCT 
                      dbo.TECDOC_TOF_LINK_LA_TYP.LAT_TYP_ID, dbo.TECDOC_TOF_LINK_GA_STR.LGS_STR_ID, dbo.TECDOC_TOF_LINK_ART.LA_ART_ID, 
                      dbo.TECDOC_TOF_LINK_ART.LA_GA_ID, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_NR, dbo.v_des_texts.TEX_TEXT AS GA_TEXT, 
                      v_des_texts_1.TEX_TEXT AS GA_STANDART_TEXT, v_des_texts_2.TEX_TEXT AS GA_ASSEMBLY_TEXT, 
                      v_des_texts_3.TEX_TEXT AS GA_INTENDED_TEXT, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_UNIVERSAL, 
                      dbo.TECDOC_TOF_ARTICLES.ART_ARTICLE_NR, dbo.TECDOC_TOF_SUPPLIERS.SUP_BRAND, v_des_texts_4.TEX_TEXT AS ART_TEXT, 
                      v_des_texts_5.TEX_TEXT AS ART_COMPLETE_TEXT, dbo.TECDOC_TOF_ARTICLES.ART_PACK_SELFSERVICE, 
                      dbo.TECDOC_TOF_ARTICLES.ART_MATERIAL_MARK, dbo.TECDOC_TOF_ARTICLES.ART_REPLACEMENT, 
                      dbo.TECDOC_TOF_ARTICLES.ART_ACCESSORY, dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE1, 
                      dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE2
FROM         dbo.TECDOC_TOF_LINK_LA_TYP INNER JOIN
                      dbo.TECDOC_TOF_LINK_GA_STR ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_LINK_GA_STR.LGS_GA_ID INNER JOIN
                      dbo.TECDOC_TOF_LINK_ART ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_LA_ID = dbo.TECDOC_TOF_LINK_ART.LA_ID INNER JOIN
                      dbo.TECDOC_TOF_ARTICLES ON dbo.TECDOC_TOF_LINK_ART.LA_ART_ID = dbo.TECDOC_TOF_ARTICLES.ART_ID INNER JOIN
                      dbo.TECDOC_TOF_GENERIC_ARTICLES ON dbo.TECDOC_TOF_LINK_ART.LA_GA_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_ID INNER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON dbo.TECDOC_TOF_ARTICLES.ART_SUP_ID = dbo.TECDOC_TOF_SUPPLIERS.SUP_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_5 ON dbo.TECDOC_TOF_ARTICLES.ART_COMPLETE_DES_ID = v_des_texts_5.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_4 ON dbo.TECDOC_TOF_ARTICLES.ART_DES_ID = v_des_texts_4.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID = dbo.v_des_texts.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_STANDARD = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_ASSEMBLY = v_des_texts_2.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_INTENDED = v_des_texts_3.DES_ID



GO

CREATE VIEW dbo.v_link_typ_str_ga_sup
AS
SELECT     dbo.TECDOC_TOF_LINK_LA_TYP.LAT_TYP_ID, dbo.TECDOC_TOF_LINK_LA_TYP.LAT_LA_ID, dbo.TECDOC_TOF_LINK_LA_TYP.LAT_SUP_ID, 
                      dbo.TECDOC_TOF_LINK_GA_STR.LGS_STR_ID, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_ID, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_NR, 
                      dbo.v_des_texts.TEX_TEXT AS GA_TEXT, v_des_texts_1.TEX_TEXT AS GA_STANDART_TEXT, v_des_texts_2.TEX_TEXT AS GA_ASSEMBLY_TEXT, 
                      v_des_texts_3.TEX_TEXT AS GA_INTENDED_TEXT, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_UNIVERSAL, 
                      dbo.TECDOC_TOF_SUPPLIERS.SUP_BRAND, dbo.TECDOC_TOF_LINK_LA_TYP.LAT_SORT
FROM         dbo.v_des_texts RIGHT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 RIGHT OUTER JOIN
                      dbo.TECDOC_TOF_LINK_LA_TYP INNER JOIN
                      dbo.TECDOC_TOF_LINK_GA_STR ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_LINK_GA_STR.LGS_GA_ID INNER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_SUP_ID = dbo.TECDOC_TOF_SUPPLIERS.SUP_ID INNER JOIN
                      dbo.TECDOC_TOF_GENERIC_ARTICLES ON 
                      dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_INTENDED = v_des_texts_3.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_ASSEMBLY = v_des_texts_2.DES_ID ON 
                      v_des_texts_1.DES_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_STANDARD ON 
                      dbo.v_des_texts.DES_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID




GO




CREATE VIEW dbo.v_str_search_tree
AS
SELECT     dbo.TECDOC_TOF_SEARCH_TREE.STR_ID, dbo.TECDOC_TOF_SEARCH_TREE.STR_ID_PARENT, dbo.TECDOC_TOF_SEARCH_TREE.STR_TYPE, 
                      dbo.TECDOC_TOF_SEARCH_TREE.STR_LEVEL, dbo.v_des_texts.TEX_TEXT AS STR_TEXT, dbo.TECDOC_TOF_SEARCH_TREE.STR_SORT, 
                      dbo.TECDOC_TOF_SEARCH_TREE.STR_NODE_NR
FROM         dbo.TECDOC_TOF_SEARCH_TREE INNER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_SEARCH_TREE.STR_DES_ID = dbo.v_des_texts.DES_ID




GO

CREATE view dbo.v_tree 
with schemabinding
as

with tree as
(
	select 
		str_id,
		str_id_parent,
		str_type,
		str_des_id,
		str_level,
		convert(varchar, str_id) as lvl
	from dbo.tecdoc_tof_search_tree 
	where str_id_parent is null
	union all
	select 
		t.str_id,
		t.str_id_parent,
		t.str_type,
		t.str_des_id,
		t.str_level,
		convert(varchar, t1.lvl + '_' + convert(varchar, t.str_id)) as lvl
	from dbo.tecdoc_tof_search_tree t
	join tree t1 on t.str_id_parent = t1.str_id
)
select 
	t.str_id,
	t.str_id_parent,
	t.str_type,
	t.str_level,
	dt.tex_text,
	t.lvl
from tree t
join dbo.tecdoc_tof_designations d on d.des_id = t.str_des_id
join dbo.tecdoc_tof_des_texts dt on dt.tex_id = d.des_tex_id
where d.des_lng_id = 16


GO


CREATE VIEW dbo.v_typ_str_art_details
AS
SELECT     dbo.v_link_typ_str_art_ga.LAT_TYP_ID, dbo.v_link_typ_str_art_ga.LGS_STR_ID, dbo.v_art_articles.ART_ARTICLE_NR, 
                      dbo.v_art_articles.SUP_BRAND, dbo.v_art_articles.ART_TEXT, dbo.v_art_articles.ART_COMPLETE_TEXT, 
                      dbo.v_art_articles.ART_PACK_SELFSERVICE, dbo.v_art_articles.ART_MATERIAL_MARK, dbo.v_art_articles.ART_REPLACEMENT, 
                      dbo.v_art_articles.ART_ACCESSORY, dbo.v_art_articles.ART_BATCH_SIZE1, dbo.v_art_articles.ART_BATCH_SIZE2, 
                      dbo.v_ga_generic_articles.GA_NR, dbo.v_ga_generic_articles.GA_TEXT, dbo.v_ga_generic_articles.GA_STANDART_TEXT, 
                      dbo.v_ga_generic_articles.GA_ASSEMBLY_TEXT, dbo.v_ga_generic_articles.GA_INTENDED_TEXT, dbo.v_ga_generic_articles.GA_UNIVERSAL
FROM         dbo.v_link_typ_str_art_ga INNER JOIN
                      dbo.v_art_articles ON dbo.v_link_typ_str_art_ga.LA_ART_ID = dbo.v_art_articles.ART_ID INNER JOIN
                      dbo.v_ga_generic_articles ON dbo.v_link_typ_str_art_ga.LA_GA_ID = dbo.v_ga_generic_articles.GA_ID




GO


CREATE VIEW dbo.v_typ_str_sup_ga_art
AS
SELECT     dbo.TECDOC_TOF_LINK_LA_TYP.LAT_TYP_ID, dbo.TECDOC_TOF_LINK_LA_TYP.LAT_SUP_ID, dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID, 
                      dbo.TECDOC_TOF_LINK_GA_STR.LGS_STR_ID, dbo.TECDOC_TOF_LINK_ART.LA_ART_ID, dbo.TECDOC_TOF_ARTICLES.ART_ARTICLE_NR, 
                      dbo.TECDOC_TOF_SUPPLIERS.SUP_BRAND, v_des_texts_4.TEX_TEXT AS ART_TEXT, v_des_texts_5.TEX_TEXT AS ART_COMPLETE_TEXT, 
                      dbo.TECDOC_TOF_ARTICLES.ART_PACK_SELFSERVICE, dbo.TECDOC_TOF_ARTICLES.ART_MATERIAL_MARK, 
                      dbo.TECDOC_TOF_ARTICLES.ART_REPLACEMENT, dbo.TECDOC_TOF_ARTICLES.ART_ACCESSORY, dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE1, 
                      dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE2, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_NR, dbo.v_des_texts.TEX_TEXT AS GA_TEXT, 
                      v_des_texts_1.TEX_TEXT AS GA_STANDART_TEXT, v_des_texts_2.TEX_TEXT AS GA_ASSEMBLY_TEXT, 
                      v_des_texts_3.TEX_TEXT AS GA_INTENDED_TEXT, dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_UNIVERSAL
FROM         dbo.v_des_texts INNER JOIN
                      dbo.v_des_texts v_des_texts_5 ON dbo.v_des_texts.DES_ID = v_des_texts_5.DES_ID RIGHT OUTER JOIN
                      dbo.TECDOC_TOF_LINK_ART INNER JOIN
                      dbo.TECDOC_TOF_ARTICLES ON dbo.TECDOC_TOF_LINK_ART.LA_ART_ID = dbo.TECDOC_TOF_ARTICLES.ART_ID INNER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON dbo.TECDOC_TOF_ARTICLES.ART_SUP_ID = dbo.TECDOC_TOF_SUPPLIERS.SUP_ID INNER JOIN
                      dbo.TECDOC_TOF_LINK_LA_TYP ON dbo.TECDOC_TOF_LINK_ART.LA_ID = dbo.TECDOC_TOF_LINK_LA_TYP.LAT_LA_ID INNER JOIN
                      dbo.TECDOC_TOF_GENERIC_ARTICLES ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_ID INNER JOIN
                      dbo.TECDOC_TOF_LINK_GA_STR ON dbo.TECDOC_TOF_LINK_LA_TYP.LAT_GA_ID = dbo.TECDOC_TOF_LINK_GA_STR.LGS_GA_ID ON 
                      v_des_texts_5.DES_ID = dbo.TECDOC_TOF_ARTICLES.ART_COMPLETE_DES_ID AND 
                      dbo.v_des_texts.DES_ID = dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_4 ON dbo.TECDOC_TOF_ARTICLES.ART_DES_ID = v_des_texts_4.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_INTENDED = v_des_texts_3.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_ASSEMBLY = v_des_texts_2.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_GENERIC_ARTICLES.GA_DES_ID_STANDARD = v_des_texts_1.DES_ID



GO

CREATE VIEW dbo.v_typ_types
AS
SELECT     dbo.TECDOC_TOF_TYPES.TYP_ID, dbo.v_cds_texts.TEX_TEXT AS TYP_TEXT, v_cds_texts_1.TEX_TEXT AS TYP_MMT_TEXT, 
                      dbo.TECDOC_TOF_TYPES.TYP_MOD_ID, dbo.TECDOC_TOF_MODELS.MOD_PC, dbo.TECDOC_TOF_MODELS.MOD_CV, 
                      dbo.TECDOC_TOF_TYPES.TYP_SORT, cast(dbo.TECDOC_TOF_TYPES.TYP_PCON_START as varchar(10)) as TYP_PCON_START, cast(dbo.TECDOC_TOF_TYPES.TYP_PCON_END as varchar(10)) as TYP_PCON_END, 
                      dbo.TECDOC_TOF_TYPES.TYP_KW_FROM, dbo.TECDOC_TOF_TYPES.TYP_KW_UPTO, dbo.TECDOC_TOF_TYPES.TYP_HP_FROM, 
                      dbo.TECDOC_TOF_TYPES.TYP_HP_UPTO, 
                      round(dbo.TECDOC_TOF_TYPES.TYP_CCM / 1000.0, 1) as TYP_CCM, 
                      dbo.TECDOC_TOF_TYPES.TYP_CYLINDERS, 
                      dbo.TECDOC_TOF_TYPES.TYP_DOORS, dbo.TECDOC_TOF_TYPES.TYP_TANK, v_des_texts_1.TEX_TEXT AS KV_ABS_TEXT, 
                      v_des_texts_2.TEX_TEXT AS KV_ASR_TEXT, v_des_texts_3.TEX_TEXT AS KV_ENGINE_TEXT, v_des_texts_7.TEX_TEXT AS KV_BRAKE_TYPE_TEXT, 
                      v_des_texts_8.TEX_TEXT AS KV_BRAKE_SYST_TEXT, v_des_texts_9.TEX_TEXT AS KV_FUEL_TEXT, 
                      v_des_texts_10.TEX_TEXT AS KV_CATALYST_TEXT, v_des_texts_11.TEX_TEXT AS KV_BODY_TEXT, 
                      v_des_texts_12.TEX_TEXT AS KV_STEERING_TEXT, v_des_texts_4.TEX_TEXT AS KV_STEERING_SIDE_TEXT, 
                      dbo.TECDOC_TOF_TYPES.TYP_MAX_WEIGHT, v_des_texts_5.TEX_TEXT AS KV_MODEL_TEXT, v_des_texts_6.TEX_TEXT AS KV_AXLE_TEXT, 
                      dbo.TECDOC_TOF_TYPES.TYP_CCM_TAX, dbo.TECDOC_TOF_TYPES.TYP_LITRES, v_des_texts_13.TEX_TEXT AS KV_DRIVE_TEXT, 
                      v_des_texts_14.TEX_TEXT AS KV_TRANS_TEXT, v_des_texts_15.TEX_TEXT AS KV_FUEL_SUPPLY_TEXT, dbo.TECDOC_TOF_TYPES.TYP_VALVES, 
                      dbo.TECDOC_TOF_TYPES.TYP_RT_EXISTS
FROM         dbo.TECDOC_TOF_TYPES INNER JOIN
                      dbo.TECDOC_TOF_MODELS ON dbo.TECDOC_TOF_TYPES.TYP_MOD_ID = dbo.TECDOC_TOF_MODELS.MOD_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_15 ON dbo.TECDOC_TOF_TYPES.TYP_KV_FUEL_SUPPLY_DES_ID = v_des_texts_15.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_14 ON dbo.TECDOC_TOF_TYPES.TYP_KV_TRANS_DES_ID = v_des_texts_14.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_13 ON dbo.TECDOC_TOF_TYPES.TYP_KV_DRIVE_DES_ID = v_des_texts_13.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_6 ON dbo.TECDOC_TOF_TYPES.TYP_KV_AXLE_DES_ID = v_des_texts_6.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_5 ON dbo.TECDOC_TOF_TYPES.TYP_KV_MODEL_DES_ID = v_des_texts_5.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_4 ON dbo.TECDOC_TOF_TYPES.TYP_KV_STEERING_SIDE_DES_ID = v_des_texts_4.DES_ID LEFT OUTER JOIN
                      dbo.v_cds_texts ON dbo.TECDOC_TOF_TYPES.TYP_CDS_ID = dbo.v_cds_texts.CDS_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_12 ON dbo.TECDOC_TOF_TYPES.TYP_KV_STEERING_DES_ID = v_des_texts_12.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_11 ON dbo.TECDOC_TOF_TYPES.TYP_KV_BODY_DES_ID = v_des_texts_11.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_10 ON dbo.TECDOC_TOF_TYPES.TYP_KV_CATALYST_DES_ID = v_des_texts_10.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_9 ON dbo.TECDOC_TOF_TYPES.TYP_KV_FUEL_DES_ID = v_des_texts_9.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_8 ON dbo.TECDOC_TOF_TYPES.TYP_KV_BRAKE_SYST_DES_ID = v_des_texts_8.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_7 ON dbo.TECDOC_TOF_TYPES.TYP_KV_BRAKE_TYPE_DES_ID = v_des_texts_7.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_3 ON dbo.TECDOC_TOF_TYPES.TYP_KV_ENGINE_DES_ID = v_des_texts_3.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_2 ON dbo.TECDOC_TOF_TYPES.TYP_KV_ASR_DES_ID = v_des_texts_2.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_TYPES.TYP_KV_ABS_DES_ID = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_TYPES.TYP_KV_VOLTAGE_DES_ID = dbo.v_des_texts.DES_ID LEFT OUTER JOIN
                      dbo.v_cds_texts v_cds_texts_1 ON dbo.TECDOC_TOF_TYPES.TYP_MMT_CDS_ID = v_cds_texts_1.CDS_ID




GO


create VIEW dbo.vArticles
WITH SCHEMABINDING 
AS
SELECT     dbo.TECDOC_TOF_ARTICLES.ART_ID, dbo.TECDOC_TOF_ARTICLES.ART_ARTICLE_NR, dbo.TECDOC_TOF_SUPPLIERS.SUP_BRAND, 
											dbo.TECDOC_TOF_SUPPLIERS.SUP_ID,
                      dbo.v_des_texts.TEX_TEXT AS ART_TEXT, v_des_texts_1.TEX_TEXT AS ART_COMPLETE_TEXT, 
                      dbo.TECDOC_TOF_ARTICLES.ART_PACK_SELFSERVICE, dbo.TECDOC_TOF_ARTICLES.ART_MATERIAL_MARK, 
                      dbo.TECDOC_TOF_ARTICLES.ART_REPLACEMENT, dbo.TECDOC_TOF_ARTICLES.ART_ACCESSORY, dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE1, 
                      dbo.TECDOC_TOF_ARTICLES.ART_BATCH_SIZE2
FROM         dbo.TECDOC_TOF_ARTICLES LEFT OUTER JOIN
                      dbo.v_des_texts v_des_texts_1 ON dbo.TECDOC_TOF_ARTICLES.ART_COMPLETE_DES_ID = v_des_texts_1.DES_ID LEFT OUTER JOIN
                      dbo.v_des_texts ON dbo.TECDOC_TOF_ARTICLES.ART_DES_ID = dbo.v_des_texts.DES_ID LEFT OUTER JOIN
                      dbo.TECDOC_TOF_SUPPLIERS ON dbo.TECDOC_TOF_ARTICLES.ART_SUP_ID = dbo.TECDOC_TOF_SUPPLIERS.SUP_ID



GO

CREATE view dbo.vParts with schemabinding
as
SELECT     
	dbo.v_link_typ_str_art_ga.LA_ART_ID, 
	dbo.v_link_typ_str_art_ga.LAT_TYP_ID, 
	dbo.v_link_typ_str_art_ga.LGS_STR_ID, 
	dbo.v_art_articles.ART_ARTICLE_NR, 
  dbo.v_art_articles.SUP_BRAND, 
  dbo.v_art_articles.ART_SUP_ID, 
  dbo.v_art_articles.ART_TEXT, 
  dbo.v_art_articles.ART_COMPLETE_TEXT, 
  dbo.v_art_articles.ART_PACK_SELFSERVICE, 
  dbo.v_art_articles.ART_MATERIAL_MARK, 
  dbo.v_art_articles.ART_REPLACEMENT, 
  dbo.v_art_articles.ART_ACCESSORY, 
  dbo.v_art_articles.ART_BATCH_SIZE1, 
  dbo.v_art_articles.ART_BATCH_SIZE2 

FROM         
	dbo.v_link_typ_str_art_ga 
	JOIN dbo.v_art_articles ON dbo.v_link_typ_str_art_ga.LA_ART_ID = dbo.v_art_articles.ART_ID 
GO
CREATE view dbo.vTypeTree
as
select 
	st.str_id,
	st.str_id_parent,
	lt.lat_typ_id as typ_id,
	m.mod_id,
	t.tex_text
from
	tecdoc_tof_search_tree st 
join tecdoc_tof_link_ga_str gs on gs.lgs_str_id = st.str_id
join tecdoc_tof_link_la_typ lt on lt.lat_ga_id = gs.lgs_ga_id
join v_des_texts t on t.des_id = st.str_des_id
join tecdoc_tof_types tt on tt.typ_id = lt.lat_typ_id
join tecdoc_tof_models m on m.mod_id = tt.typ_mod_id
where
	st.str_type = 1
	
GO

CREATE SCHEMA Custom AUTHORIZATION dbo
GO

IF OBJECT_ID('Custom.CountryDeliveries', 'U') IS NOT NULL DROP TABLE Custom.CountryDeliveries
CREATE TABLE Custom.CountryDeliveries(
	TypeID int NOT NULL,
	CountryID int NOT NULL,
	ManufacturerID int NOT NULL,
	ModelID int NOT NULL
 CONSTRAINT PK_CountryDeliveries PRIMARY KEY CLUSTERED 
(
	TypeID ASC,
	CountryID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

insert into Custom.CountryDeliveries(TypeID, ManufacturerID, ModelID, CountryID)
select 
t.typ_id, m.mod_id, mm.mfa_id, c.cou_id
from dbo.tecdoc_tof_countries c
join dbo.tecdoc_tof_types t on substring(typ_ctm, c.cou_id + 2, 1) = 1
join dbo.tecdoc_tof_models m on m.mod_id = t.typ_mod_id
join dbo.tecdoc_tof_manufacturers mm on mm.mfa_id = m.mod_mfa_id

GO

CREATE NONCLUSTERED INDEX IDX_All ON Custom.CountryDeliveries
(
	CountryID ASC
)
INCLUDE ( TypeID,
ManufacturerID,
ModelID) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO


IF OBJECT_ID('Custom.VisibleItems', 'U') IS NOT NULL DROP TABLE Custom.VisibleItems
CREATE TABLE Custom.VisibleItems(
	mfa_id int NOT NULL,
	mod_id int NOT NULL,
	typ_id int NOT NULL,
 CONSTRAINT PK_VisibleItems PRIMARY KEY CLUSTERED 
(
	mfa_id ASC,
	mod_id ASC,
	typ_id ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
insert into Custom.VisibleItems(typ_id, mod_id, mfa_id)
select distinct
	t.typ_id,
	m.mod_id,
	mm.mfa_id
from tecdoc_tof_link_la_typ lt
join tecdoc_tof_types t on t.typ_id = lt.lat_typ_id
join tecdoc_tof_models m on m.mod_id = t.typ_mod_id
join tecdoc_tof_manufacturers mm on mm.mfa_id = m.mod_mfa_id
order by mfa_Id


-------------------------------------------------------
-- Добавление новых названий с неверной кодировкой
-- и исправление уже известных названий на правильные
-- возможно, потребуется изменить название БД в скрипте, если оно изменится на сервере
--------------------------------------------------------

insert into ex_rmsauto_store.Tecdoc.NameCorrections(OriginalName, CorrectedName, TableName, ID)
select 
	mfa_brand, 
	mfa_brand,
	'tecdoc_tof_manufacturers',
	mfa_id
from 
	tecdoc_tof_manufacturers 
where 
	mfa_brand like '%?%'
	and lower(mfa_brand) not in (select lower(OriginalName) from ex_rmsauto_store.Tecdoc.NameCorrections)
	 
insert into ex_rmsauto_store.Tecdoc.NameCorrections(OriginalName, CorrectedName, TableName, ID)
select 
	tex_text, 
	tex_text,
	'tecdoc_tof_models',
	m.mod_id
from 
	tecdoc_tof_models m 
join v_cds_texts t on m.mod_cds_id = t.cds_id
where
	t.tex_text like '%?%'
	and lower(tex_text) not in (select lower(OriginalName) from ex_rmsauto_store.Tecdoc.NameCorrections)
	
	
GO

update m
set m.mfa_brand = n.CorrectedName
from tecdoc_tof_manufacturers m 
join ex_rmsauto_store.Tecdoc.NameCorrections n on lower(m.mfa_brand) = lower(n.OriginalName)

GO

update t
set t.tex_text = n.CorrectedName
from tecdoc_tof_des_texts t 
join tecdoc_tof_country_designations cd on cd.cds_tex_id = t.tex_id
join tecdoc_tof_models m on m.mod_cds_id = cd.cds_id
join ex_rmsauto_store.Tecdoc.NameCorrections n on lower(n.OriginalName) = lower(t.tex_text)
where
	cd.cds_lng_id in (16,255)
	
GO
	
-- sgolubev

CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_LA_TYP_c_62_2133582639__K3_K2] ON [dbo].[TECDOC_TOF_LINK_LA_TYP] 
(
	[LAT_GA_ID] ASC,
	[LAT_LA_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO

CREATE STATISTICS [_dta_stat_1493580359_2_3] ON [dbo].[TECDOC_TOF_GRAPHICS]([GRA_ID], [GRA_DOC_TYPE])

GO

-- на всякий случай

CREATE NONCLUSTERED INDEX [IX_TECDOC_TOF_LINK_ART] ON [dbo].[TECDOC_TOF_LINK_ART] 
(
	[LA_GA_ID] ASC,
	[LA_ART_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO

--	sgolubev Долго делается

CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_LINK_LA_TYP_c_62_2133582639__K3_K2] ON [dbo].[TECDOC_TOF_LINK_LA_TYP] 
(
	[LAT_GA_ID] ASC,
	[LAT_LA_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

GO

CREATE STATISTICS [_dta_stat_2005582183_2_1] ON [dbo].[TECDOC_TOF_LINK_GRA_ART]([LGA_SORT], [LGA_ART_ID])

GO

--	sgolubev Денормализуем языковые таблицы

select dsgn.des_id as [ID], max(txts.tex_text) AS [TEXT] into [Custom].[DenormalizedDesTexts]
from TECDOC_TOF_DES_TEXTS txts
join TECDOC_TOF_DESIGNATIONS dsgn on txts.TEX_ID = dsgn.DES_TEX_ID
where (dsgn.DES_LNG_ID = 16 OR dsgn.DES_LNG_ID = 255)
group by dsgn.des_id
order by dsgn.des_id

go

select cdsgn.CDS_ID as [ID], max(txts.tex_text) AS [TEXT] into [Custom].[DenormalizedCdsTexts]
from TECDOC_TOF_DES_TEXTS txts
join TECDOC_TOF_COUNTRY_DESIGNATIONS cdsgn on txts.TEX_ID = cdsgn.CDS_TEX_ID
where (cdsgn.CDS_LNG_ID = 16 OR cdsgn.CDS_LNG_ID = 255)
group by cdsgn.CDS_ID
order by cdsgn.CDS_ID

go

ALTER TABLE [Custom].[DenormalizedDesTexts] ADD CONSTRAINT PK_DenormalizedDesTexts PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE = ON, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

ALTER TABLE [Custom].[DenormalizedCdsTexts] ADD CONSTRAINT PK_DenormalizedCdsTexts PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE = ON, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO

--	sgolubev Для поисковых запросов (проверка на существование номера у разных производителей)

CREATE NONCLUSTERED INDEX [_dta_index_TECDOC_TOF_ARTICLES_62_949578421__K2_K3_K5] ON [dbo].[TECDOC_TOF_ARTICLES] 
(
	[ART_ARTICLE_NR] ASC,
	[ART_SUP_ID] ASC,
	[ART_COMPLETE_DES_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS [_dta_stat_949578421_5_2] ON [dbo].[TECDOC_TOF_ARTICLES]([ART_COMPLETE_DES_ID], [ART_ARTICLE_NR])
go

CREATE STATISTICS [_dta_stat_949578421_3_2_5] ON [dbo].[TECDOC_TOF_ARTICLES]([ART_SUP_ID], [ART_ARTICLE_NR], [ART_COMPLETE_DES_ID])
go

CREATE STATISTICS [_dta_stat_1093578934_6_2] ON [dbo].[TECDOC_TOF_ART_LOOKUP]([ARL_DISPLAY_NR], [ARL_SEARCH_NUMBER])
go

--	sgolubev Для поисковых запросов вообще (кластерный индекс по поисковому артиклю для TECDOC_TOF_ART_LOOKUP)
--	Строится дооолго

CREATE CLUSTERED INDEX [_dta_index_TECDOC_TOF_ART_LOOKUP_c_62_1093578934__K2] ON [dbo].[TECDOC_TOF_ART_LOOKUP] 
(
	[ARL_SEARCH_NUMBER] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]