using System.Web.UI;



[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.migrate.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.t.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.plus.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.volvo.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.ford.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.css.qgroups.groups.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.vehicle.unitlist-floated.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.mousewheel.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.expand_loading.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.mb.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderTopLeft.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderTopCenter.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.css.unit.unit.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.spacer.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.closed.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.overlay.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderBottomCenter.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.unit.unit.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.dimensions.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.openned.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.seat.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.mb-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.honda.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.chevrolet.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.pointer.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.replacement-backward.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.minus.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.expand_plus.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.vw-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.seat-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.renault.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.move.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.mouse_wheel.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderTopRight.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.replacement-forward.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.cart.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.i_half.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.landrover.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.hino.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.mouse.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.filter.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.i.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.toyota.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.subaru.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.nud.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.hyundai-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.audi-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.css.common.colorbox.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.info.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.bmw.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.tooltip.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.dragscrollable.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.open.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.closed.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.suzuki.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.opel.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.kia-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.infinity.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.unit.spacer.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.l.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.yamaha.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.skoda.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.audi.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.isuzu.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.lmb.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderMiddleLeft.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.details.detailslist.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.open.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.loading.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.skoda-w.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.mitsubishi.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.mazda.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.mmb.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderBottomLeft.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.details.images.replacement.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.leaf.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.loading_background.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.filter.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.document.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.vw.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.peugeot.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.nissan.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.kia.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.zoom.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.expand_minus.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.fuso.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.noimage.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderMiddleRight.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.border.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.qgroups.groups.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.scripts.common.jquery.colorbox.js", "application/x-javascript")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.i_bhalf.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.kawasaki.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.hyundai.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.rmb.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.qgroups.expand_leaf.gif", "image/gif")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.daihatsu.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.ie6.borderBottomRight.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.common.controls.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.css.common.guayaquil.css", "text/css", PerformSubstitution = true)]

//недостающие ресурсы (соответствующие картинки должны быть помечены как "embedded resource"
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.abarth.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.alfa romeo.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.citroen.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.fiat.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.fiat professional.png", "image/png")]
[assembly: WebResource("Laximo.Guayaquil.Render.Assets.images.catalogs.lancia.png", "image/png")]

// ReSharper disable EmptyNamespace
namespace Laximo.Guayaquil.Render
// ReSharper restore EmptyNamespace
{
}
