//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmsAuto.Store.Web.Cms {
    
    
    public partial class VinRequestAccessDenied {
        
        /// <summary>
        /// _leftMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RmsAuto.Store.Web.Controls.LeftMenu _leftMenu;
        
        /// <summary>
        /// _pageHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RmsAuto.Store.Web.Controls.PageHeader _pageHeader;
        
        /// <summary>
        /// TextBlock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RmsAuto.Store.Web.Cms.TextItems.TextItemControl TextBlock;
        
        /// <summary>
        /// _btnDefault control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink _btnDefault;
    }
}
