//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmsAuto.Store.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RmsAuto.Store.Web.Resource.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All closed.
        /// </summary>
        internal static string ComplexStatusFilter_Completed {
            get {
                return ResourceManager.GetString("ComplexStatusFilter_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All in work.
        /// </summary>
        internal static string ComplexStatusFilter_NotCompleted {
            get {
                return ResourceManager.GetString("ComplexStatusFilter_NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require confirm.
        /// </summary>
        internal static string ComplexStatusFilter_RequiresReaction {
            get {
                return ResourceManager.GetString("ComplexStatusFilter_RequiresReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат товара.
        /// </summary>
        internal static string LightPaymentType_GoodsReturn {
            get {
                return ResourceManager.GetString("LightPaymentType_GoodsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат денег.
        /// </summary>
        internal static string LightPaymentType_PayBack {
            get {
                return ResourceManager.GetString("LightPaymentType_PayBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        internal static string LightPaymentType_Payment {
            get {
                return ResourceManager.GetString("LightPaymentType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отгрузка.
        /// </summary>
        internal static string LightPaymentType_Shipping {
            get {
                return ResourceManager.GetString("LightPaymentType_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате поставки (возр.).
        /// </summary>
        internal static string OrderLineSortFields_EstSupplyDateAsc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_EstSupplyDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате поставки (убыв.).
        /// </summary>
        internal static string OrderLineSortFields_EstSupplyDateDesc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_EstSupplyDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По производителю, номеру детали.
        /// </summary>
        internal static string OrderLineSortFields_Manufacturer {
            get {
                return ResourceManager.GetString("OrderLineSortFields_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По номеру заказа (возр.), производителю, номеру детали.
        /// </summary>
        internal static string OrderLineSortFields_OrderIDAsc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_OrderIDAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По номеру заказа (убыв.), производителю, номеру детали.
        /// </summary>
        internal static string OrderLineSortFields_OrderIDDesc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_OrderIDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По наименованию.
        /// </summary>
        internal static string OrderLineSortFields_PartName {
            get {
                return ResourceManager.GetString("OrderLineSortFields_PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По цене (возр.).
        /// </summary>
        internal static string OrderLineSortFields_PriceAsc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_PriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По цене (убыв.).
        /// </summary>
        internal static string OrderLineSortFields_PriceDesc {
            get {
                return ResourceManager.GetString("OrderLineSortFields_PriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По статусу.
        /// </summary>
        internal static string OrderLineSortFields_Status {
            get {
                return ResourceManager.GetString("OrderLineSortFields_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По номеру заказа (возр.).
        /// </summary>
        internal static string OrderSortFields_OrderIdAsc {
            get {
                return ResourceManager.GetString("OrderSortFields_OrderIdAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По номеру  заказа (убыв.).
        /// </summary>
        internal static string OrderSortFields_OrderIdDesc {
            get {
                return ResourceManager.GetString("OrderSortFields_OrderIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По статусу.
        /// </summary>
        internal static string OrderSortFields_Status {
            get {
                return ResourceManager.GetString("OrderSortFields_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to принят.
        /// </summary>
        internal static string OrderStatus_Apply {
            get {
                return ResourceManager.GetString("OrderStatus_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завершен.
        /// </summary>
        internal static string OrderStatus_Completed {
            get {
                return ResourceManager.GetString("OrderStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новый.
        /// </summary>
        internal static string OrderStatus_New {
            get {
                return ResourceManager.GetString("OrderStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в работе.
        /// </summary>
        internal static string OrderStatus_Processing {
            get {
                return ResourceManager.GetString("OrderStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to наличный расчёт.
        /// </summary>
        internal static string PaymentMethod_Cash {
            get {
                return ResourceManager.GetString("PaymentMethod_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to безналичный расчёт.
        /// </summary>
        internal static string PaymentMethod_Clearing {
            get {
                return ResourceManager.GetString("PaymentMethod_Clearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В порядке ввода.
        /// </summary>
        internal static string SortOptions_InputOrder {
            get {
                return ResourceManager.GetString("SortOptions_InputOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производитель, артикул.
        /// </summary>
        internal static string SortOptions_ManufacturerArticle {
            get {
                return ResourceManager.GetString("SortOptions_ManufacturerArticle", resourceCulture);
            }
        }
    }
}
