//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

namespace Laximo.Guayaquil.Data.Entities
{ // 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FindVehicleByVIN {
    
        private VehicleInfo[] rowField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public VehicleInfo[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VehicleInfo {
    
        private int vehicleidField;
    
        private string modelField;
    
        private string nameField;
    
        private string gradeField;
    
        private string transmissionField;
    
        private string doorsField;
    
        private string creationregionField;
    
        private string destinationregionField;
    
        private string dateField;
    
        private string manufacturedField;
    
        private string framecolorField;
    
        private string trimcolorField;
    
        private string datefromField;
    
        private string datetoField;
    
        private string frameField;
    
        private string framesField;
    
        private string framefromField;
    
        private string frametoField;
    
        private string engineField;
    
        private string engine1Field;
    
        private string engine2Field;
    
        private string enginenoField;
    
        private string optionsField;
    
        private string modelyearfromField;
    
        private string modelyeartoField;
    
        private string modificationField;
    
        private string descriptionField;
    
        private string catalogField;
    
        private string ssdField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int vehicleid {
            get {
                return this.vehicleidField;
            }
            set {
                this.vehicleidField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transmission {
            get {
                return this.transmissionField;
            }
            set {
                this.transmissionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string doors {
            get {
                return this.doorsField;
            }
            set {
                this.doorsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creationregion {
            get {
                return this.creationregionField;
            }
            set {
                this.creationregionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationregion {
            get {
                return this.destinationregionField;
            }
            set {
                this.destinationregionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string manufactured {
            get {
                return this.manufacturedField;
            }
            set {
                this.manufacturedField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string framecolor {
            get {
                return this.framecolorField;
            }
            set {
                this.framecolorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimcolor {
            get {
                return this.trimcolorField;
            }
            set {
                this.trimcolorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datefrom {
            get {
                return this.datefromField;
            }
            set {
                this.datefromField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dateto {
            get {
                return this.datetoField;
            }
            set {
                this.datetoField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string frames {
            get {
                return this.framesField;
            }
            set {
                this.framesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string framefrom {
            get {
                return this.framefromField;
            }
            set {
                this.framefromField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string frameto {
            get {
                return this.frametoField;
            }
            set {
                this.frametoField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string engine {
            get {
                return this.engineField;
            }
            set {
                this.engineField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string engine1 {
            get {
                return this.engine1Field;
            }
            set {
                this.engine1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string engine2 {
            get {
                return this.engine2Field;
            }
            set {
                this.engine2Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string engineno {
            get {
                return this.enginenoField;
            }
            set {
                this.enginenoField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelyearfrom {
            get {
                return this.modelyearfromField;
            }
            set {
                this.modelyearfromField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelyearto {
            get {
                return this.modelyeartoField;
            }
            set {
                this.modelyeartoField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modification {
            get {
                return this.modificationField;
            }
            set {
                this.modificationField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ssd {
            get {
                return this.ssdField;
            }
            set {
                this.ssdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FindVehicleByFrame {
    
        private VehicleInfo[] rowField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public VehicleInfo[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FindVehicleByWizard {
    
        private VehicleInfo[] rowField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public VehicleInfo[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }
}