<?xml version="1.0" encoding="utf-8"?>
<Database Name="ex_rmsauto_log" Class="LogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=1ctest;Initial Catalog=ex_rmsauto_log;Integrated Security=True;Persist Security Info=True" SettingsObjectName="RmsAuto.Store.Properties.Settings" SettingsPropertyName="ex_rmsauto_logConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SearchSparePartsLog" Member="SearchSparePartsLogs">
    <Type Name="SearchSparePartsLog">
      <Column Name="SearchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientIP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SearchSparePartsWebServiceLog" Member="SearchSparePartsWebServiceLogs">
    <Type Name="SearchSparePartsWebServiceLog">
      <Column Name="SearchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientIP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>