<?xml version="1.0" encoding="utf-8"?><Database Name="ex_apecautoR_log" Class="LogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=W2008R2SQL1\SQL1;Initial Catalog=ex_apecautoR_log;Integrated Security=True" SettingsObjectName="RmsAuto.Store.Properties.Settings" SettingsPropertyName="ex_rmsauto_logConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SearchSparePartsLog" Member="SearchSparePartsLogs">
    <Type Name="SearchSparePartsLog">
      <Column Name="SearchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientIP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SearchSparePartsWebServiceLog" Member="SearchSparePartsWebServiceLogs">
    <Type Name="SearchSparePartsWebServiceLog">
      <Column Name="SearchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientIP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.CreateEvent" Method="CreateEvent">
    <Parameter Name="data" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>