//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exceptions", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная цена.
        /// </summary>
        internal static string BadPrice {
            get {
                return ResourceManager.GetString("BadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество указано неверно.
        /// </summary>
        internal static string BadQty {
            get {
                return ResourceManager.GetString("BadQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенный код не совпадает.
        /// </summary>
        internal static string CaptchaBad {
            get {
                return ResourceManager.GetString("CaptchaBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не ввели код подтверждения.
        /// </summary>
        internal static string CaptchaEmpty {
            get {
                return ResourceManager.GetString("CaptchaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент Вы привязаны к несуществующему пункту выдачи Ваших заказов. Для изменения пункта выдачи, просьба обращаться к менеджерам оптового или розничного отделов..
        /// </summary>
        internal static string Cart_ErrorClientStore {
            get {
                return ResourceManager.GetString("Cart_ErrorClientStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент Вы привязаны к несуществующему пункту выдачи Ваших заказов. Свяжитесь с нашим менеджером по телефону {0}..
        /// </summary>
        internal static string Cart_ErrorClientStoreLight {
            get {
                return ResourceManager.GetString("Cart_ErrorClientStoreLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка в системе. Попробуйте повторить свой запрос позднее. Если ошибка будет повторяться свяжитесь с нами по телефону..
        /// </summary>
        internal static string CommonException {
            get {
                return ResourceManager.GetString("CommonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат электроннного адреса.
        /// </summary>
        internal static string EMailIsInvalid {
            get {
                return ResourceManager.GetString("EMailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не ввели электронный адрес.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите наименование.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество.
        /// </summary>
        internal static string EnterQty {
            get {
                return ResourceManager.GetString("EnterQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не ввели текст в это поле.
        /// </summary>
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно быть введено русскими буквами.
        /// </summary>
        internal static string FirstNameShouldBeCyrillic {
            get {
                return ResourceManager.GetString("FirstNameShouldBeCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный символ.
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия должна быть введена русскими буквами.
        /// </summary>
        internal static string LastNameShouldBeCyrillic {
            get {
                return ResourceManager.GetString("LastNameShouldBeCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум с id={0} не найден в базе.
        /// </summary>
        internal static string NoForumFound {
            get {
                return ResourceManager.GetString("NoForumFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных форума и сайта рассинхронизованы. В базе сайта не найден пользователь с UserId={0}.
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина пароля должна быть от 1 до 10 символов.
        /// </summary>
        internal static string PasswordLengthIsInvalid {
            get {
                return ResourceManager.GetString("PasswordLengthIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество должно быть введено русскими буквами.
        /// </summary>
        internal static string PatronimicNameShouldBeCyrillic {
            get {
                return ResourceManager.GetString("PatronimicNameShouldBeCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность должна быть введена русскими буквами.
        /// </summary>
        internal static string PositionShouldBeCyrillic {
            get {
                return ResourceManager.GetString("PositionShouldBeCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, задайте id необходимого форума.
        /// </summary>
        internal static string SetForumIdParamater {
            get {
                return ResourceManager.GetString("SetForumIdParamater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат данных (17 символов, все символы - цифры и латиница, кроме I, O и Q)..
        /// </summary>
        internal static string VinRequest_BadVin {
            get {
                return ResourceManager.GetString("VinRequest_BadVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала сохраните редакируемую позицию..
        /// </summary>
        internal static string VinRequest_ItemsEditing {
            get {
                return ResourceManager.GetString("VinRequest_ItemsEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали ни одной желаемой позиции. Нажмите на кнопку &quot;Добавить&quot;..
        /// </summary>
        internal static string VinRequest_NoItems {
            get {
                return ResourceManager.GetString("VinRequest_NoItems", resourceCulture);
            }
        }
    }
}
