//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImagesURL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagesURL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ImagesURL", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/add_btn.gif.
        /// </summary>
        internal static string add_btn {
            get {
                return ResourceManager.GetString("add_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/basket_img.jpg.
        /// </summary>
        internal static string basket_img {
            get {
                return ResourceManager.GetString("basket_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/basket_img_top3.jpg.
        /// </summary>
        internal static string basket_img_top3 {
            get {
                return ResourceManager.GetString("basket_img_top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/bask_cencel.gif.
        /// </summary>
        internal static string bask_cencel {
            get {
                return ResourceManager.GetString("bask_cencel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/bask_nextstep.gif.
        /// </summary>
        internal static string bask_nextstep {
            get {
                return ResourceManager.GetString("bask_nextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/bask_prevstep.gif.
        /// </summary>
        internal static string bask_prevstep {
            get {
                return ResourceManager.GetString("bask_prevstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/bask_send.gif.
        /// </summary>
        internal static string bask_send {
            get {
                return ResourceManager.GetString("bask_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_load.gif.
        /// </summary>
        internal static string btn_load {
            get {
                return ResourceManager.GetString("btn_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_reg.gif.
        /// </summary>
        internal static string btn_reg {
            get {
                return ResourceManager.GetString("btn_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_search_catalog.gif.
        /// </summary>
        internal static string btn_search_catalog {
            get {
                return ResourceManager.GetString("btn_search_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_search_catalog_accum.gif.
        /// </summary>
        internal static string btn_search_catalog_accum {
            get {
                return ResourceManager.GetString("btn_search_catalog_accum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/oil_catalog.gif.
        /// </summary>
        internal static string btn_search_oil {
            get {
                return ResourceManager.GetString("btn_search_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_search_tires.gif.
        /// </summary>
        internal static string btn_search_tires {
            get {
                return ResourceManager.GetString("btn_search_tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/btn_search_vin.gif.
        /// </summary>
        internal static string btn_search_vin {
            get {
                return ResourceManager.GetString("btn_search_vin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/cart_add.gif.
        /// </summary>
        internal static string cart_add {
            get {
                return ResourceManager.GetString("cart_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/cart_issue.gif.
        /// </summary>
        internal static string cart_issue {
            get {
                return ResourceManager.GetString("cart_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/car_edit.gif.
        /// </summary>
        internal static string car_edit {
            get {
                return ResourceManager.GetString("car_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/catalog_nonoriginals_img.jpg.
        /// </summary>
        internal static string catalog_nonoriginals_img {
            get {
                return ResourceManager.GetString("catalog_nonoriginals_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/catalog_originals_img.jpg.
        /// </summary>
        internal static string catalog_originals_img {
            get {
                return ResourceManager.GetString("catalog_originals_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/enter_btn.jpg.
        /// </summary>
        internal static string enter_btn {
            get {
                return ResourceManager.GetString("enter_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/faq_img.jpg.
        /// </summary>
        internal static string faq_img {
            get {
                return ResourceManager.GetString("faq_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/filter_btn.gif.
        /// </summary>
        internal static string filter_btn {
            get {
                return ResourceManager.GetString("filter_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/header_img_manager.jpg.
        /// </summary>
        internal static string header_img_manager {
            get {
                return ResourceManager.GetString("header_img_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/header-r-ru.png.
        /// </summary>
        internal static string header_img_new {
            get {
                return ResourceManager.GetString("header_img_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/help_img.png.
        /// </summary>
        internal static string help_img {
            get {
                return ResourceManager.GetString("help_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/login_btn.gif.
        /// </summary>
        internal static string login_btn {
            get {
                return ResourceManager.GetString("login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/logoff_title.gif.
        /// </summary>
        internal static string logoff_title {
            get {
                return ResourceManager.GetString("logoff_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/manufacturers_img.png.
        /// </summary>
        internal static string manufacturers_img {
            get {
                return ResourceManager.GetString("manufacturers_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/nextstep.gif.
        /// </summary>
        internal static string nextstep {
            get {
                return ResourceManager.GetString("nextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/partners_img.png.
        /// </summary>
        internal static string partners_img {
            get {
                return ResourceManager.GetString("partners_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/prevstep.gif.
        /// </summary>
        internal static string prevstep {
            get {
                return ResourceManager.GetString("prevstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/print_btn.gif.
        /// </summary>
        internal static string print_btn {
            get {
                return ResourceManager.GetString("print_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/print_logo.png.
        /// </summary>
        internal static string print_logo {
            get {
                return ResourceManager.GetString("print_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/reg_btn.jpg.
        /// </summary>
        internal static string reg_btn {
            get {
                return ResourceManager.GetString("reg_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/reg_img.jpg.
        /// </summary>
        internal static string reg_img {
            get {
                return ResourceManager.GetString("reg_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/reg_login.gif.
        /// </summary>
        internal static string reg_login {
            get {
                return ResourceManager.GetString("reg_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/rurs_img.jpg.
        /// </summary>
        internal static string rurs_img {
            get {
                return ResourceManager.GetString("rurs_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/save_btn.gif.
        /// </summary>
        internal static string save_btn {
            get {
                return ResourceManager.GetString("save_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/search_img.jpg.
        /// </summary>
        internal static string search_img {
            get {
                return ResourceManager.GetString("search_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/send_btn.gif.
        /// </summary>
        internal static string send_btn {
            get {
                return ResourceManager.GetString("send_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/show_btn.gif.
        /// </summary>
        internal static string show_btn {
            get {
                return ResourceManager.GetString("show_btn", resourceCulture);
            }
        }
    }
}
