//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Requests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Requests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Requests", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все рекламации принимаются не позднее {0} календарных дней со дня отгрузки товара!.
        /// </summary>
        internal static string AlertText {
            get {
                return ResourceManager.GetString("AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для запроса детализированного баланса укажите период:.
        /// </summary>
        internal static string BalancePeriodInfo {
            get {
                return ResourceManager.GetString("BalancePeriodInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация баланса.
        /// </summary>
        internal static string BalanceRequest {
            get {
                return ResourceManager.GetString("BalanceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этом разделе можно запросить баланс.
        /// </summary>
        internal static string BalanceRequestInfo {
            get {
                return ResourceManager.GetString("BalanceRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформление заявок на отказ/возврат возможно только из статусов &apos;поступил на склад&apos; и &apos;получен клиентом&apos;!.
        /// </summary>
        internal static string BLExceptionHint {
            get {
                return ResourceManager.GetString("BLExceptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат обработки данного запроса будет выслан на Ваш e-mail адрес, указанный при регистрации..
        /// </summary>
        internal static string EmailProcessingResults {
            get {
                return ResourceManager.GetString("EmailProcessingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат будет отправлен на Ваш e-mail адрес, указанный при регистрации..
        /// </summary>
        internal static string EmailResults {
            get {
                return ResourceManager.GetString("EmailResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер заказа.
        /// </summary>
        internal static string EnterTheOrderNo {
            get {
                return ResourceManager.GetString("EnterTheOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите артикул.
        /// </summary>
        internal static string EnterThePartNo {
            get {
                return ResourceManager.GetString("EnterThePartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одной строки в указанном заказе, удовлетворяющей условию непоставки!.
        /// </summary>
        internal static string FailedFindLines {
            get {
                return ResourceManager.GetString("FailedFindLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить данные об указанном заказе, возможно номер заказа не существует!.
        /// </summary>
        internal static string FailedUploadData {
            get {
                return ResourceManager.GetString("FailedUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш запрос обработан..
        /// </summary>
        internal static string RequestProceeded {
            get {
                return ResourceManager.GetString("RequestProceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки запроса..
        /// </summary>
        internal static string RequestProcessingError {
            get {
                return ResourceManager.GetString("RequestProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте повторить запрос позднее..
        /// </summary>
        internal static string RequestTryAgain {
            get {
                return ResourceManager.GetString("RequestTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос о непоставке.
        /// </summary>
        internal static string StatusRequest {
            get {
                return ResourceManager.GetString("StatusRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос о непоставке деталей.
        /// </summary>
        internal static string StatusRequestFull {
            get {
                return ResourceManager.GetString("StatusRequestFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этом разделе можно запросить  дату поставки запчастей со статусами «задержка» и «отправлено поставщику»..
        /// </summary>
        internal static string StatusRequestInfo {
            get {
                return ResourceManager.GetString("StatusRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш запрос будет обработан в течении 24 часов..
        /// </summary>
        internal static string YourRequestWillProcessed24 {
            get {
                return ResourceManager.GetString("YourRequestWillProcessed24", resourceCulture);
            }
        }
    }
}
